# Stage 5: LLM-Based Few-Shot Relation Extraction

## Project
**Comparing LLMs and Fine-Tuned Transformer-Based Models for Biomedical Named Entity Recognition and Relation Extraction for Knowledge Graph Construction**

## Objective
The objective of Stage 5 is to perform **few-shot biomedical relation extraction** on the BioRED dataset using **Qwen2.5-7B-Instruct**.

The model will be provided with biomedical text and predefined entity pairs and will predict the relationship between those entities according to the BioRED relation schema.

This stage reuses the infrastructure developed during Stage 4 wherever possible, including:

- Qwen2.5-7B-Instruct model and tokenizer
- 4-bit quantized model loading
- Few-shot prompting framework
- Structured JSON generation
- JSON parsing and validation
- Batch inference
- Checkpoint saving
- Resume capability
- Evaluation framework

The NER-specific components from Stage 4 will be adapted for relation classification.

## Stage 5 Pipeline

1. Load and inspect the prepared BioRED relation extraction data
2. Define the relation extraction schema
3. Prepare few-shot relation examples
4. Construct the relation extraction prompt
5. Load Qwen2.5-7B-Instruct
6. Perform and validate single-example inference
7. Run development-set inference
8. Evaluate development performance
9. Freeze the final few-shot prompt
10. Run test-set inference and evaluation
11. Compare LLM-based RE with fine-tuned PubMedBERT RE

In [1]:
# Stage 5.1A - Mount Google Drive and Set Project Path

from google.colab import drive
drive.mount("/content/drive")

from pathlib import Path

PROJECT_DIR = Path("/content/drive/MyDrive/Capstone_Project")

print("Project directory:", PROJECT_DIR)
print("Exists:", PROJECT_DIR.exists())

Mounted at /content/drive
Project directory: /content/drive/MyDrive/Capstone_Project
Exists: True

In [2]:
# Stage 5.1B - Define Stage 5 Paths and Inspect Saved RE Outputs

from pathlib import Path

STAGE_3_2_DIR = PROJECT_DIR / "Stage_3_2_Outputs"
STAGE_5_DIR = PROJECT_DIR / "Stage_5_LLM_RE"

STAGE_5_DIR.mkdir(parents=True, exist_ok=True)

print("Stage 3.2 outputs directory:", STAGE_3_2_DIR)
print("Exists:", STAGE_3_2_DIR.exists())

print("\nStage 5 output directory:", STAGE_5_DIR)
print("Exists:", STAGE_5_DIR.exists())

print("\nFiles available in Stage_3_2_Outputs:")

if STAGE_3_2_DIR.exists():
    for file_path in sorted(STAGE_3_2_DIR.iterdir()):
        print("-", file_path.name)
else:
    print("Stage_3_2_Outputs directory not found.")

Stage 3.2 outputs directory: /content/drive/MyDrive/Capstone_Project/Stage_3_2_Outputs
Exists: True

Stage 5 output directory: /content/drive/MyDrive/Capstone_Project/Stage_5_LLM_RE
Exists: True

Files available in Stage_3_2_Outputs:
- biored_prepared_relation_data.pkl
- biored_relation_label_mappings.pkl

In [3]:
# Stage 5.1C - Load Prepared Relation Data and Label Mappings

import pickle

RELATION_DATA_PATH = STAGE_3_2_DIR / "biored_prepared_relation_data.pkl"
LABEL_MAPPING_PATH = STAGE_3_2_DIR / "biored_relation_label_mappings.pkl"

with open(RELATION_DATA_PATH, "rb") as f:
    relation_data = pickle.load(f)

with open(LABEL_MAPPING_PATH, "rb") as f:
    relation_label_mappings = pickle.load(f)

print("Relation data type:", type(relation_data))
print("Relation data keys:", relation_data.keys())

print("\nLabel mappings type:", type(relation_label_mappings))
print("Label mapping keys:", relation_label_mappings.keys())

Relation data type: <class 'dict'>
Relation data keys: dict_keys(['train', 'development', 'test'])

Label mappings type: <class 'dict'>
Label mapping keys: dict_keys(['label_to_id', 'id_to_label'])

In [4]:
print("\nDataset sizes:")

for split_name, split_data in relation_data.items():
    print(f"{split_name}: {len(split_data)} examples")

print("\nLabel mappings:")
print(relation_label_mappings)

print("\nFirst training example:")
print(relation_data["train"][0])

Dataset sizes:
train: 8356 examples
development: 2324 examples
test: 2326 examples

Label mappings:
{'label_to_id': {'Association': 0, 'Bind': 1, 'Comparison': 2, 'Conversion': 3, 'Cotreatment': 4, 'Drug_Interaction': 5, 'Negative_Correlation': 6, 'Positive_Correlation': 7, 'No_Relation': 8}, 'id_to_label': {0: 'Association', 1: 'Bind', 2: 'Comparison', 3: 'Conversion', 4: 'Cotreatment', 5: 'Drug_Interaction', 6: 'Negative_Correlation', 7: 'Positive_Correlation', 8: 'No_Relation'}}

First training example:
{'document_id': '26115410', 'text': 'Mechanisms Underlying Latent Disease Risk Associated with Early-Life Arsenic Exposure: Current Research Trends and Scientific Gaps. BACKGROUND: Millions of individuals worldwide, particularly those living in rural and developing areas, are exposed to harmful levels of inorganic arsenic (iAs) in their drinking water. Inorganic As exposure during key developmental periods is associated with a variety of adverse health effects including those that are evident in adulthood. There is considerable interest in identifying the molecular mechanisms that relate early-life iAs exposure to the development of these latent diseases, particularly in relationship to cancer. OBJECTIVES: This work summarizes research on the molecular mechanisms that underlie the increased risk of cancer development in adulthood that is associated with early-life iAs exposure. DISCUSSION: Epigenetic reprogramming that imparts functional changes in gene expression, the development of cancer stem cells, and immunomodulation are plausible underlying mechanisms by which early-life iAs exposure elicits latent carcinogenic effects. CONCLUSIONS: Evidence is mounting that relates early-life iAs exposure and cancer development later in life. Future research should include animal studies that address mechanistic hypotheses and studies of human populations that integrate early-life exposure, molecular alterations, and latent disease outcomes.', 'entity1_identifier': 'D001152', 'entity1_annotation_id': '1', 'entity1_text': 'inorganic arsenic', 'entity1_type': 'ChemicalEntity', 'entity1_start': 269, 'entity1_end': 286, 'entity2_identifier': 'D009369', 'entity2_annotation_id': '5', 'entity2_text': 'cancer', 'entity2_type': 'DiseaseOrPhenotypicFeature', 'entity2_start': 659, 'entity2_end': 665, 'relation_label': 'Positive_Correlation', 'relation_label_id': 7, 'marked_text': 'Mechanisms Underlying Latent Disease Risk Associated with Early-Life Arsenic Exposure: Current Research Trends and Scientific Gaps. BACKGROUND: Millions of individuals worldwide, particularly those living in rural and developing areas, are exposed to harmful levels of @ChemicalEntity$ inorganic arsenic @/ChemicalEntity$ (iAs) in their drinking water. Inorganic As exposure during key developmental periods is associated with a variety of adverse health effects including those that are evident in adulthood. There is considerable interest in identifying the molecular mechanisms that relate early-life iAs exposure to the development of these latent diseases, particularly in relationship to #DiseaseOrPhenotypicFeature$ cancer #/DiseaseOrPhenotypicFeature$. OBJECTIVES: This work summarizes research on the molecular mechanisms that underlie the increased risk of cancer development in adulthood that is associated with early-life iAs exposure. DISCUSSION: Epigenetic reprogramming that imparts functional changes in gene expression, the development of cancer stem cells, and immunomodulation are plausible underlying mechanisms by which early-life iAs exposure elicits latent carcinogenic effects. CONCLUSIONS: Evidence is mounting that relates early-life iAs exposure and cancer development later in life. Future research should include animal studies that address mechanistic hypotheses and studies of human populations that integrate early-life exposure, molecular alterations, and latent disease outcomes.', 'input_ids': [2, 3138, 4443, 10079, 2174, 2209, 2138, 1715, 2743, 16, 2978, 11513, 3035, 29, 3040, 2698, 7472, 1690, 6993, 11491, 17, 2645, 29, 21665, 1685, 3415, 7525, 15, 4124, 2415, 5126, 1682, 7016, 1690, 4510, 3655, 15, 1810, 4183, 1701, 12910, 2182, 1685, 35, 3829, 1865, 2677, 7, 10326, 11513, 35, 18, 3829, 1865, 2677, 7, 11, 27525, 12, 1682, 2076, 7055, 2972, 17, 10326, 1732, 3035, 2098, 3784, 5638, 5904, 1744, 2138, 1715, 42, 4692, 1685, 4246, 2161, 2228, 2574, 2415, 1760, 1810, 7460, 1682, 10759, 17, 2100, 1744, 6394, 4826, 1682, 6656, 1680, 2894, 3138, 1760, 11832, 2743, 16, 2978, 27525, 3035, 1701, 1680, 2418, 1685, 1898, 10079, 3316, 15, 4124, 1682, 2953, 1701, 6, 2174, 2588, 23162, 2677, 17511, 7335, 2327, 7, 2310, 6, 18, 2174, 2588, 23162, 2677, 17511, 7335, 2327, 7, 17, 4283, 29, 1805, 2626, 11626, 2698, 1755, 1680, 2894, 3138, 1760, 13481, 1680, 2165, 2209, 1685, 2310, 2418, 1682, 10759, 1760, 1744, 2138, 1715, 2743, 16, 2978, 27525, 3035, 17, 6372, 29, 9693, 19882, 1760, 27595, 1727, 2913, 2458, 1682, 2397, 2181, 15, 1680, 2418, 1685, 2310, 4223, 1933, 15, 1690, 12549, 2041, 1810, 16480, 4443, 3138, 1772, 1950, 2743, 16, 2978, 27525, 3035, 21217, 10079, 15361, 2228, 17, 2547, 29, 2739, 1744, 24415, 1760, 17370, 2743, 16, 2978, 27525, 3035, 1690, 2310, 2418, 4511, 1682, 2978, 17, 3886, 2698, 2821, 4285, 4331, 2223, 1760, 5695, 9809, 10490, 1690, 2223, 1685, 2323, 4012, 1760, 13762, 2743, 16, 2978, 3035, 15, 2894, 5199, 15, 1690, 10079, 2174, 3247, 17, 3], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [5]:
# Stage 5.1D - Validate Prepared Relation Extraction Data

required_fields = {
    "document_id",
    "text",
    "entity1_text",
    "entity1_type",
    "entity2_text",
    "entity2_type",
    "relation_label",
    "marked_text",
}

valid_labels = set(relation_label_mappings["label_to_id"].keys())

for split_name, split_data in relation_data.items():

    missing_field_examples = 0
    invalid_label_examples = 0
    missing_marked_text_examples = 0

    for example in split_data:

        # Check required fields
        if not required_fields.issubset(example.keys()):
            missing_field_examples += 1

        # Check relation label
        if example.get("relation_label") not in valid_labels:
            invalid_label_examples += 1

        # Check marked text
        if not example.get("marked_text"):
            missing_marked_text_examples += 1

    print(f"\n{split_name.upper()}")
    print("Total examples:", len(split_data))
    print("Missing required fields:", missing_field_examples)
    print("Invalid relation labels:", invalid_label_examples)
    print("Missing marked text:", missing_marked_text_examples)

TRAIN
Total examples: 8356
Missing required fields: 0
Invalid relation labels: 0
Missing marked text: 0

DEVELOPMENT
Total examples: 2324
Missing required fields: 0
Invalid relation labels: 0
Missing marked text: 0

TEST
Total examples: 2326
Missing required fields: 0
Invalid relation labels: 0
Missing marked text: 0

In [4]:
# Stage 5.2A - Define Relation Labels and Structured Output Schema

RELATION_LABELS = list(
    relation_label_mappings["label_to_id"].keys()
)

RELATION_OUTPUT_SCHEMA = {
    "relation": "<one valid BioRED relation label>"
}

print("Relation labels:")
for label in RELATION_LABELS:
    print("-", label)

print("\nExpected JSON output:")
print(RELATION_OUTPUT_SCHEMA)

Relation labels:
- Association
- Bind
- Comparison
- Conversion
- Cotreatment
- Drug_Interaction
- Negative_Correlation
- Positive_Correlation
- No_Relation

Expected JSON output:
{'relation': '<one valid BioRED relation label>'}

In [5]:
# Stage 5.2B - Create Relation Output Validation Function

def validate_relation_output(parsed_output):
    """
    Validate a parsed LLM relation extraction output.

    Expected format:
        {"relation": "<valid BioRED relation label>"}

    Returns:
        (is_valid, relation, error_message)
    """

    # Output must be a dictionary
    if not isinstance(parsed_output, dict):
        return False, None, "Output is not a dictionary."

    # Required field must exist
    if "relation" not in parsed_output:
        return False, None, "Missing 'relation' field."

    relation = parsed_output["relation"]

    # Relation must be a string
    if not isinstance(relation, str):
        return False, None, "'relation' must be a string."

    # Remove accidental surrounding whitespace
    relation = relation.strip()

    # Relation must belong to the BioRED schema
    if relation not in RELATION_LABELS:
        return False, None, f"Invalid relation label: {relation}"

    return True, relation, None

In [6]:
valid_example = {
    "relation": "Positive_Correlation"
}

invalid_example = {
    "relation": "Causes"
}

print("Valid example:")
print(validate_relation_output(valid_example))

print("\nInvalid example:")
print(validate_relation_output(invalid_example))

Valid example:
(True, 'Positive_Correlation', None)

Invalid example:
(False, None, 'Invalid relation label: Causes')

In [7]:
# Stage 5.2C - Create JSON Parsing Function

import json
import re

def parse_relation_json(raw_output):
    """
    Parse JSON from the raw LLM output.

    Returns:
        (parsed_output, error_message)
    """

    if not isinstance(raw_output, str):
        return None, "Raw output is not a string."

    text = raw_output.strip()

    # Remove Markdown code fences if present
    text = re.sub(r"^```(?:json)?\s*", "", text, flags=re.IGNORECASE)
    text = re.sub(r"\s*```$", "", text)

    # First try parsing the full output directly
    try:
        return json.loads(text), None
    except json.JSONDecodeError:
        pass

    # If extra text is present, try extracting the first JSON object
    match = re.search(r"\{.*?\}", text, flags=re.DOTALL)

    if match:
        try:
            return json.loads(match.group()), None
        except json.JSONDecodeError as error:
            return None, f"Invalid JSON: {error}"

    return None, "No JSON object found."

In [8]:
test_outputs = [
    '{"relation": "Positive_Correlation"}',

    '''```json
    {"relation": "Bind"}
    ```''',

    'The answer is {"relation": "Association"}',

    'relation = Positive_Correlation'
]

for i, output in enumerate(test_outputs, start=1):

    parsed, error = parse_relation_json(output)

    print(f"\nTest {i}")
    print("Parsed:", parsed)
    print("Error:", error)

Test 1
Parsed: {'relation': 'Positive_Correlation'}
Error: None

Test 2
Parsed: {'relation': 'Bind'}
Error: None

Test 3
Parsed: {'relation': 'Association'}
Error: None

Test 4
Parsed: None
Error: No JSON object found.

In [9]:
# Stage 5.2D - Create Combined Parsing and Validation Function

def process_relation_output(raw_output):
    """
    Parse and validate a raw LLM relation extraction output.

    Returns:
        {
            "valid_json": bool,
            "valid_relation": bool,
            "relation": str or None,
            "error": str or None
        }
    """

    parsed_output, parse_error = parse_relation_json(raw_output)

    if parsed_output is None:
        return {
            "valid_json": False,
            "valid_relation": False,
            "relation": None,
            "error": parse_error
        }

    is_valid, relation, validation_error = validate_relation_output(
        parsed_output
    )

    if not is_valid:
        return {
            "valid_json": True,
            "valid_relation": False,
            "relation": None,
            "error": validation_error
        }

    return {
        "valid_json": True,
        "valid_relation": True,
        "relation": relation,
        "error": None
    }

In [10]:
test_outputs = [
    '{"relation": "Positive_Correlation"}',
    '{"relation": "Causes"}',
    'not valid json'
]

for i, output in enumerate(test_outputs, start=1):
    result = process_relation_output(output)

    print(f"\nTest {i}")
    print(result)

Test 1
{'valid_json': True, 'valid_relation': True, 'relation': 'Positive_Correlation', 'error': None}

Test 2
{'valid_json': True, 'valid_relation': False, 'relation': None, 'error': 'Invalid relation label: Causes'}

Test 3
{'valid_json': False, 'valid_relation': False, 'relation': None, 'error': 'No JSON object found.'}

In [14]:
# Stage 5.3A - Inspect Training Relation Label Distribution

from collections import Counter

train_label_counts = Counter(
    example["relation_label"]
    for example in relation_data["train"]
)

print("Training relation label distribution:\n")

for label in RELATION_LABELS:
    print(f"{label}: {train_label_counts[label]}")

total_train_examples = len(relation_data["train"])

print("\nTraining relation label percentages:\n")

for label in RELATION_LABELS:
    count = train_label_counts[label]
    percentage = (count / total_train_examples) * 100

    print(
        f"{label}: "
        f"{count} examples "
        f"({percentage:.2f}%)"
    )

Training relation label distribution:

Association: 2192
Bind: 61
Comparison: 28
Conversion: 3
Cotreatment: 31
Drug_Interaction: 11
Negative_Correlation: 763
Positive_Correlation: 1089
No_Relation: 4178

Training relation label percentages:

Association: 2192 examples (26.23%)
Bind: 61 examples (0.73%)
Comparison: 28 examples (0.34%)
Conversion: 3 examples (0.04%)
Cotreatment: 31 examples (0.37%)
Drug_Interaction: 11 examples (0.13%)
Negative_Correlation: 763 examples (9.13%)
Positive_Correlation: 1089 examples (13.03%)
No_Relation: 4178 examples (50.00%)

In [15]:
# Stage 5.3B - Inspect Candidate Few-Shot Example Lengths

candidates_by_label = {}

for label in RELATION_LABELS:

    label_examples = [
        example
        for example in relation_data["train"]
        if example["relation_label"] == label
    ]

    # Sort by marked-text character length
    label_examples = sorted(
        label_examples,
        key=lambda example: len(example["marked_text"])
    )

    candidates_by_label[label] = label_examples

    print(f"\n{label}")
    print("Available examples:", len(label_examples))

    for i, example in enumerate(label_examples[:3], start=1):
        print(
            f"Candidate {i}: "
            f"Document {example['document_id']} | "
            f"{len(example['marked_text'])} characters | "
            f"{example['entity1_text']} -> {example['entity2_text']}"
        )

Association
Available examples: 2192
Candidate 1: Document 7468724 | 425 characters | terbutaline -> corticosteroid
Candidate 2: Document 7468724 | 449 characters | Cardiovascular complications -> terbutaline
Candidate 3: Document 18262054 | 575 characters | Y245X -> G246X

Bind
Available examples: 61
Candidate 1: Document 10661407 | 1081 characters | Langerin -> mannose
Candidate 2: Document 19463742 | 1098 characters | melanocortin -> Melanocortin-4 receptor
Candidate 3: Document 22051099 | 1186 characters | CXCR1 -> interleukin 8

Comparison
Available examples: 28
Candidate 1: Document 9746003 | 835 characters | carbamazepine -> vigabatrin
Candidate 2: Document 18631865 | 1069 characters | calcineurin inhibitors -> sirolimus
Candidate 3: Document 16920333 | 1388 characters | carbamazepine -> oxcarbazepine

Conversion
Available examples: 3
Candidate 1: Document 17391797 | 1589 characters | phosphatidylethanolamine -> phosphatidylcholine
Candidate 2: Document 16506214 | 1780 characters | arachidonic acid -> prostaglandins
Candidate 3: Document 21070631 | 1857 characters | dopamine -> noradrenaline

Cotreatment
Available examples: 31
Candidate 1: Document 9746003 | 835 characters | sodium valproate -> lamotrigine
Candidate 2: Document 9746003 | 835 characters | lamotrigine -> ethosuximide
Candidate 3: Document 9746003 | 835 characters | sodium valproate -> ethosuximide

Drug_Interaction
Available examples: 11
Candidate 1: Document 19642243 | 733 characters | tenofovir -> vancomycin
Candidate 2: Document 20533999 | 1358 characters | methamphetamine -> Dopamine
Candidate 3: Document 24927617 | 1387 characters | simvastatin -> antiviral drugs

Negative_Correlation
Available examples: 763
Candidate 1: Document 7468724 | 449 characters | terbutaline -> preterm labor
Candidate 2: Document 7468724 | 449 characters | preterm labor -> corticosteroid
Candidate 3: Document 15602202 | 565 characters | corticosteroid -> interstitial nephritis

Positive_Correlation
Available examples: 1089
Candidate 1: Document 7468724 | 449 characters | Cardiovascular complications -> corticosteroid
Candidate 2: Document 15602202 | 565 characters | antibiotic -> renal injury
Candidate 3: Document 15602202 | 565 characters | interstitial nephritis -> azithromycin

No_Relation
Available examples: 4178
Candidate 1: Document 15602202 | 539 characters | corticosteroid -> patients
Candidate 2: Document 15602202 | 539 characters | antibiotic -> patients
Candidate 3: Document 18262054 | 571 characters | G246X -> human

In [16]:
# Stage 5.3C - Inspect Few-Shot Candidate Examples

NUM_CANDIDATES_TO_INSPECT = 3

for label in RELATION_LABELS:

    print("\n" + "=" * 100)
    print(f"RELATION LABEL: {label}")
    print("=" * 100)

    candidates = candidates_by_label[label][:NUM_CANDIDATES_TO_INSPECT]

    for i, example in enumerate(candidates, start=1):

        print(f"\nCandidate {i}")
        print("Document ID:", example["document_id"])
        print(
            f"Entity 1: {example['entity1_text']} "
            f"({example['entity1_type']})"
        )
        print(
            f"Entity 2: {example['entity2_text']} "
            f"({example['entity2_type']})"
        )
        print("Gold relation:", example["relation_label"])
        print("\nMarked text:")
        print(example["marked_text"])
        print("-" * 100)

====================================================================================================
RELATION LABEL: Association
====================================================================================================

Candidate 1
Document ID: 7468724
Entity 1: terbutaline (ChemicalEntity)
Entity 2: corticosteroid (ChemicalEntity)
Gold relation: Association

Marked text:
Cardiovascular complications associated with @ChemicalEntity$ terbutaline @/ChemicalEntity$ treatment for preterm labor. Severe cardiovascular complications occurred in eight of 160 patients treated with terbutaline for preterm labor. Associated #ChemicalEntity$ corticosteroid #/ChemicalEntity$ therapy and twin gestations appear to be predisposing factors. Potential mechanisms of the pathophysiology are briefly discussed.
----------------------------------------------------------------------------------------------------

Candidate 2
Document ID: 7468724
Entity 1: Cardiovascular complications (DiseaseOrPhenotypicFeature)
Entity 2: terbutaline (ChemicalEntity)
Gold relation: Association

Marked text:
@DiseaseOrPhenotypicFeature$ Cardiovascular complications @/DiseaseOrPhenotypicFeature$ associated with #ChemicalEntity$ terbutaline #/ChemicalEntity$ treatment for preterm labor. Severe cardiovascular complications occurred in eight of 160 patients treated with terbutaline for preterm labor. Associated corticosteroid therapy and twin gestations appear to be predisposing factors. Potential mechanisms of the pathophysiology are briefly discussed.
----------------------------------------------------------------------------------------------------

Candidate 3
Document ID: 18262054
Entity 1: Y245X (SequenceVariant)
Entity 2: G246X (SequenceVariant)
Gold relation: Association

Marked text:
A family with two consecutive nonsense mutations in BMPR1A causing juvenile polyposis. We describe a novel germline mutation of BMPR1A in a family with juvenile polyposis and colon cancer. This mutation consists of two consecutive substitutions (735-6 TG>AT) that cause two nonsense mutations (@SequenceVariant$ Y245X @/SequenceVariant$, #SequenceVariant$ G246X #/SequenceVariant$), inherited in an autosomal dominant fashion, on one parental chromosome. This mutation caused protein truncation, and represents a novel case of consecutive nonsense mutations in human disease.
----------------------------------------------------------------------------------------------------

====================================================================================================
RELATION LABEL: Bind
====================================================================================================

Candidate 1
Document ID: 10661407
Entity 1: Langerin (GeneOrGeneProduct)
Entity 2: mannose (ChemicalEntity)
Gold relation: Bind

Marked text:
@GeneOrGeneProduct$ Langerin @/GeneOrGeneProduct$, a novel C-type lectin specific to Langerhans cells, is an endocytic receptor that induces the formation of Birbeck granules. We have identified a type II Ca2+-dependent lectin displaying #ChemicalEntity$ mannose #/ChemicalEntity$-binding specificity, exclusively expressed by Langerhans cells (LC), and named Langerin. LC are uniquely characterized by Birbeck granules (BG), which are organelles consisting of superimposed and zippered membranes. Here, we have shown that Langerin is constitutively associated with BG and that antibody to Langerin is internalized into these structures. Remarkably, transfection of Langerin cDNA into fibroblasts created a compact network of membrane structures with typical features of BG. Langerin is thus a potent inducer of membrane superimposition and zippering leading to BG formation. Our data suggest that induction of BG is a consequence of the antigen-capture function of Langerin, allowing routing into these organelles and providing access to a nonclassical antigen-processing pathway.
----------------------------------------------------------------------------------------------------

Candidate 2
Document ID: 19463742
Entity 1: melanocortin (GeneOrGeneProduct)
Entity 2: Melanocortin-4 receptor (GeneOrGeneProduct)
Gold relation: Bind

Marked text:
#GeneOrGeneProduct$ Melanocortin-4 receptor #/GeneOrGeneProduct$ activation inhibits c-Jun N-terminal kinase activity and promotes insulin signaling. The @GeneOrGeneProduct$ melanocortin @/GeneOrGeneProduct$ system is crucial to regulation of energy homeostasis. The melanocortin receptor type 4 (MC4R) modulates insulin signaling via effects on c-Jun N-terminal kinase (JNK). The melanocortin agonist NDP-MSH dose-dependently inhibited JNK activity in HEK293 cells stably expressing the human MC4R; effects were reversed by melanocortin receptor antagonist. NDP-MSH time- and dose-dependently inhibited IRS-1(ser307) phosphorylation, effects also reversed by a specific melanocortin receptor antagonist. NDP-MSH augmented insulin-stimulated AKT phosphorylation in vitro. The melanocortin agonist melanotan II increased insulin-stimulated AKT phosphorylation in the rat hypothalamus in vivo. NDP-MSH increased insulin-stimulated glucose uptake in hypothalamic GT1-1 cells. The current study shows that the melanocortinergic system interacts with insulin signaling via novel effects on JNK activity.
----------------------------------------------------------------------------------------------------

Candidate 3
Document ID: 22051099
Entity 1: CXCR1 (GeneOrGeneProduct)
Entity 2: interleukin 8 (GeneOrGeneProduct)
Gold relation: Bind

Marked text:
Variation in the @GeneOrGeneProduct$ CXCR1 @/GeneOrGeneProduct$ gene (IL8RA) is not associated with susceptibility to chronic periodontitis. BACKGROUND: The chemokine receptor 1 CXCR-1 (or IL8R-alpha) is a specific receptor for the #GeneOrGeneProduct$ interleukin 8 #/GeneOrGeneProduct$ (IL-8), which is chemoattractant for neutrophils and has an important role in the inflammatory response. The polymorphism rs2234671 at position Ex2+860G>C of the CXCR1 gene causes a conservative amino acid substitution (S276T). This single nucleotide polymorphism (SNP) seemed to be functional as it was associated with decreased lung cancer risk. Previous studies of our group found association of haplotypes in the IL8 and in the CXCR2 genes with the multifactorial disease chronic periodontitis. In this study we investigated the polymorphism rs2234671 in 395 Brazilian subjects with and without chronic periodontitis. FINDINGS: Similar distribution of the allelic and genotypic frequencies were observed between the groups (p>0.05). CONCLUSIONS: The polymorphism rs2234671 in the CXCR1 gene was not associated with the susceptibility to chronic periodontitis in the studied Brazilian population.
----------------------------------------------------------------------------------------------------

====================================================================================================
RELATION LABEL: Comparison
====================================================================================================

Candidate 1
Document ID: 9746003
Entity 1: carbamazepine (ChemicalEntity)
Entity 2: vigabatrin (ChemicalEntity)
Gold relation: Comparison

Marked text:
Inappropriate use of @ChemicalEntity$ carbamazepine @/ChemicalEntity$ and #ChemicalEntity$ vigabatrin #/ChemicalEntity$ in typical absence seizures. Carbamazepine and vigabatrin are contraindicated in typical absence seizures. Of 18 consecutive referrals of children with resistant typical absences only, eight were erroneously treated with carbamazepine either as monotherapy or as an add-on. Vigabatrin was also used in the treatment of two children. Frequency of absences increased in four children treated with carbamazepine and two of these developed myoclonic jerks, which resolved on withdrawal of carbamazepine. Absences were aggravated in both cases where vigabatrin was added on to concurrent treatment. Optimal control of the absences was achieved with sodium valproate, lamotrigine, or ethosuximide alone or in combination.
----------------------------------------------------------------------------------------------------

Candidate 2
Document ID: 18631865
Entity 1: calcineurin inhibitors (ChemicalEntity)
Entity 2: sirolimus (ChemicalEntity)
Gold relation: Comparison

Marked text:
mToR inhibitors-induced proteinuria: mechanisms, significance, and management. Massive urinary protein excretion has been observed after conversion from @ChemicalEntity$ calcineurin inhibitors @/ChemicalEntity$ to mammalian target of rapamycin (mToR) inhibitors, especially #ChemicalEntity$ sirolimus #/ChemicalEntity$, in renal transplant recipients with chronic allograft nephropathy. Because proteinuria is a major predictive factor of poor transplantation outcome, many studies focused on this adverse event during the past years. Whether proteinuria was due to sirolimus or only a consequence of calcineurin inhibitors withdrawal remained unsolved until high range proteinuria has been observed during sirolimus therapy in islet transplantation and in patients who received sirolimus de novo. Podocyte injury and focal segmental glomerulosclerosis have been related to mToR inhibition in some patients, but the pathways underlying these lesions remain hypothetic. We discuss herein the possible mechanisms and the significance of mToR blockade-induced proteinuria.
----------------------------------------------------------------------------------------------------

Candidate 3
Document ID: 16920333
Entity 1: carbamazepine (ChemicalEntity)
Entity 2: oxcarbazepine (ChemicalEntity)
Gold relation: Comparison

Marked text:
Anticonvulsant effect of eslicarbazepine acetate (BIA 2-093) on seizures induced by microperfusion of picrotoxin in the hippocampus of freely moving rats. Eslicarbazepine acetate (BIA 2-093, S-(-)-10-acetoxy-10,11-dihydro-5H-dibenzo/b,f/azepine-5-carboxamide) is a novel antiepileptic drug, now in Phase III clinical trials, designed with the aim of improving efficacy and safety in comparison with the structurally related drugs @ChemicalEntity$ carbamazepine @/ChemicalEntity$ (CBZ) and #ChemicalEntity$ oxcarbazepine #/ChemicalEntity$ (OXC). We have studied the effects of oral treatment with eslicarbazepine acetate on a whole-animal model in which partial seizures can be elicited repeatedly on different days without changes in threshold or seizure patterns. In the animals treated with threshold doses of picrotoxin, the average number of seizures was 2.3+/-1.2, and average seizure duration was 39.5+/-8.4s. Pre-treatment with a dose of 30 mg/kg 2h before picrotoxin microperfusion prevented seizures in the 75% of the rats. Lower doses (3 and 10mg/kg) did not suppress seizures, however, after administration of 10mg/kg, significant reductions in seizures duration (24.3+/-6.8s) and seizure number (1.6+/-0.34) were found. No adverse effects of eslicarbazepine acetate were observed in the behavioral/EEG patterns studied, including sleep/wakefulness cycle, at the doses studied.
----------------------------------------------------------------------------------------------------

====================================================================================================
RELATION LABEL: Conversion
====================================================================================================

Candidate 1
Document ID: 17391797
Entity 1: phosphatidylethanolamine (ChemicalEntity)
Entity 2: phosphatidylcholine (ChemicalEntity)
Gold relation: Conversion

Marked text:
The phosphatidylethanolamine N-methyltransferase gene V175M single nucleotide polymorphism confers the susceptibility to NASH in Japanese population. BACKGROUND/AIMS: The genetic predisposition on the development of nonalcoholic steatohepatitis (NASH) has been poorly understood. A functional polymorphism Val175Met was reported in phosphatidylethanolamine N-methyltransferase (PEMT) that catalyzes the conversion of @ChemicalEntity$ phosphatidylethanolamine @/ChemicalEntity$ to #ChemicalEntity$ phosphatidylcholine #/ChemicalEntity$. The aim of this study was to investigate whether the carriers of Val175Met variant impaired in PEMT activity are more susceptible to NASH. METHODS: Blood samples of 107 patients with biopsy-proven NASH and of 150 healthy volunteers were analyzed by the polymerase chain reaction (PCR) and restriction fragment length polymorphism. RESULTS: Val175Met variant allele of the PEMT gene was significantly more frequent in NASH patients than in healthy volunteers (p<0.001), and carriers of Val175Met variant were significantly more frequent in NASH patients than in healthy volunteers (p<0.01). Among NASH patients, body mass index was significantly lower (p<0.05), and non-obese patients were significantly more frequent (p<0.001) in carriers of Val175Met variant than in homozygotes of wild type PEMT. CONCLUSIONS: Val175Met variant of PEMT could be a candidate molecule that determines the susceptibility to NASH, because it is more frequently observed in NASH patients and non-obese persons with Val175Met variant of PEMT are facilitated to develop NASH.
----------------------------------------------------------------------------------------------------

Candidate 2
Document ID: 16506214
Entity 1: arachidonic acid (ChemicalEntity)
Entity 2: prostaglandins (ChemicalEntity)
Gold relation: Conversion

Marked text:
Genetic variation in the COX-2 gene and the association with prostate cancer risk. COX-2 is a key enzyme in the conversion of @ChemicalEntity$ arachidonic acid @/ChemicalEntity$ to #ChemicalEntity$ prostaglandins #/ChemicalEntity$. The prostaglandins produced by COX-2 are involved in inflammation and pain response in different tissues in the body. Accumulating evidence from epidemiologic studies, chemical carcinogen-induced rodent models and clinical trials indicate that COX-2 plays a role in human carcinogenesis and is overexpressed in prostate cancer tissue. We examined whether sequence variants in the COX-2 gene are associated with prostate cancer risk. We analyzed a large population-based case-control study, cancer prostate in Sweden (CAPS) consisting of 1,378 cases and 782 controls. We evaluated 16 single nucleotide polymorphisms (SNPs) spanning the entire COX-2 gene in 94 subjects of the control group. Five SNPs had a minor allele frequency of more than 5% in our study population and these were genotyped in all case patients and control subjects and gene-specific haplotypes were constructed. A statistically significant difference in allele frequency between cases and controls was observed for 2 of the SNPs (+3100 T/G and +8365 C/T), with an odds ratio of 0.78 (95% CI=0.64-0.96) and 0.65 (95% CI=0.45-0.94) respectively. In the haplotype analysis, 1 haplotype carrying the variant allele from both +3100 T/G and +8365 C/T, with a population frequency of 3%, was also significantly associated with decreased risk of prostate cancer (p=0.036, global simulated p-value=0.046). This study supports the hypothesis that inflammation is involved in prostate carcinogenesis and that sequence variation within the COX-2 gene influence the risk of prostate cancer.
----------------------------------------------------------------------------------------------------

Candidate 3
Document ID: 21070631
Entity 1: dopamine (ChemicalEntity)
Entity 2: noradrenaline (ChemicalEntity)
Gold relation: Conversion

Marked text:
The dopamine b-hydroxylase -1021C/T polymorphism is associated with the risk of Alzheimer's disease in the Epistasis Project. BACKGROUND: The loss of noradrenergic neurones of the locus coeruleus is a major feature of Alzheimer's disease (AD). Dopamine b-hydroxylase (DBH) catalyses the conversion of @ChemicalEntity$ dopamine @/ChemicalEntity$ to #ChemicalEntity$ noradrenaline #/ChemicalEntity$. Interactions have been reported between the low-activity -1021T allele (rs1611115) of DBH and polymorphisms of the pro-inflammatory cytokine genes, IL1A and IL6, contributing to the risk of AD. We therefore examined the associations with AD of the DBH -1021T allele and of the above interactions in the Epistasis Project, with 1757 cases of AD and 6294 elderly controls. METHODS: We genotyped eight single nucleotide polymorphisms (SNPs) in the three genes, DBH, IL1A and IL6. We used logistic regression models and synergy factor analysis to examine potential interactions and associations with AD. RESULTS: We found that the presence of the -1021T allele was associated with AD: odds ratio = 1.2 (95% confidence interval: 1.06-1.4, p = 0.005). This association was nearly restricted to men < 75 years old: odds ratio = 2.2 (1.4-3.3, 0.0004). We also found an interaction between the presence of DBH -1021T and the -889TT genotype (rs1800587) of IL1A: synergy factor = 1.9 (1.2-3.1, 0.005). All these results were consistent between North Europe and North Spain. CONCLUSIONS: Extensive, previous evidence (reviewed here) indicates an important role for noradrenaline in the control of inflammation in the brain. Thus, the -1021T allele with presumed low activity may be associated with misregulation of inflammation, which could contribute to the onset of AD. We suggest that such misregulation is the predominant mechanism of the association we report here.
----------------------------------------------------------------------------------------------------

====================================================================================================
RELATION LABEL: Cotreatment
====================================================================================================

Candidate 1
Document ID: 9746003
Entity 1: sodium valproate (ChemicalEntity)
Entity 2: lamotrigine (ChemicalEntity)
Gold relation: Cotreatment

Marked text:
Inappropriate use of carbamazepine and vigabatrin in typical absence seizures. Carbamazepine and vigabatrin are contraindicated in typical absence seizures. Of 18 consecutive referrals of children with resistant typical absences only, eight were erroneously treated with carbamazepine either as monotherapy or as an add-on. Vigabatrin was also used in the treatment of two children. Frequency of absences increased in four children treated with carbamazepine and two of these developed myoclonic jerks, which resolved on withdrawal of carbamazepine. Absences were aggravated in both cases where vigabatrin was added on to concurrent treatment. Optimal control of the absences was achieved with @ChemicalEntity$ sodium valproate @/ChemicalEntity$, #ChemicalEntity$ lamotrigine #/ChemicalEntity$, or ethosuximide alone or in combination.
----------------------------------------------------------------------------------------------------

Candidate 2
Document ID: 9746003
Entity 1: lamotrigine (ChemicalEntity)
Entity 2: ethosuximide (ChemicalEntity)
Gold relation: Cotreatment

Marked text:
Inappropriate use of carbamazepine and vigabatrin in typical absence seizures. Carbamazepine and vigabatrin are contraindicated in typical absence seizures. Of 18 consecutive referrals of children with resistant typical absences only, eight were erroneously treated with carbamazepine either as monotherapy or as an add-on. Vigabatrin was also used in the treatment of two children. Frequency of absences increased in four children treated with carbamazepine and two of these developed myoclonic jerks, which resolved on withdrawal of carbamazepine. Absences were aggravated in both cases where vigabatrin was added on to concurrent treatment. Optimal control of the absences was achieved with sodium valproate, @ChemicalEntity$ lamotrigine @/ChemicalEntity$, or #ChemicalEntity$ ethosuximide #/ChemicalEntity$ alone or in combination.
----------------------------------------------------------------------------------------------------

Candidate 3
Document ID: 9746003
Entity 1: sodium valproate (ChemicalEntity)
Entity 2: ethosuximide (ChemicalEntity)
Gold relation: Cotreatment

Marked text:

In [12]:
# Stage 5.3D - Select and Freeze Few-Shot Demonstrations

FEW_SHOT_SELECTION = [
    {
        "relation_label": "Association",
        "document_id": "7468724",
        "entity1_text": "Cardiovascular complications",
        "entity2_text": "terbutaline",
    },
    {
        "relation_label": "Bind",
        "document_id": "10661407",
        "entity1_text": "Langerin",
        "entity2_text": "mannose",
    },
    {
        "relation_label": "Comparison",
        "document_id": "16920333",
        "entity1_text": "carbamazepine",
        "entity2_text": "oxcarbazepine",
    },
    {
        "relation_label": "Conversion",
        "document_id": "17391797",
        "entity1_text": "phosphatidylethanolamine",
        "entity2_text": "phosphatidylcholine",
    },
    {
        "relation_label": "Cotreatment",
        "document_id": "9746003",
        "entity1_text": "sodium valproate",
        "entity2_text": "lamotrigine",
    },
    {
        "relation_label": "Drug_Interaction",
        "document_id": "19642243",
        "entity1_text": "tenofovir",
        "entity2_text": "vancomycin",
    },
    {
        "relation_label": "Negative_Correlation",
        "document_id": "7468724",
        "entity1_text": "terbutaline",
        "entity2_text": "preterm labor",
    },
    {
        "relation_label": "Positive_Correlation",
        "document_id": "15602202",
        "entity1_text": "interstitial nephritis",
        "entity2_text": "azithromycin",
    },
    {
        "relation_label": "No_Relation",
        "document_id": "18262054",
        "entity1_text": "G246X",
        "entity2_text": "human",
    },
]
def find_training_example(selection):
    """
    Find one exact training example matching the frozen
    few-shot selection specification.
    """

    matches = [
        example
        for example in relation_data["train"]
        if (
            example["document_id"] == selection["document_id"]
            and example["relation_label"] == selection["relation_label"]
            and example["entity1_text"] == selection["entity1_text"]
            and example["entity2_text"] == selection["entity2_text"]
        )
    ]

    if len(matches) != 1:
        raise ValueError(
            f"Expected exactly one match for {selection}, "
            f"but found {len(matches)}."
        )

    return matches[0]


few_shot_examples = [
    find_training_example(selection)
    for selection in FEW_SHOT_SELECTION
]

print("Number of frozen few-shot examples:", len(few_shot_examples))

for i, example in enumerate(few_shot_examples, start=1):
    print(
        f"{i}. {example['relation_label']} | "
        f"{example['entity1_text']} -> {example['entity2_text']} | "
        f"Document {example['document_id']}"
    )

Number of frozen few-shot examples: 9
1. Association | Cardiovascular complications -> terbutaline | Document 7468724
2. Bind | Langerin -> mannose | Document 10661407
3. Comparison | carbamazepine -> oxcarbazepine | Document 16920333
4. Conversion | phosphatidylethanolamine -> phosphatidylcholine | Document 17391797
5. Cotreatment | sodium valproate -> lamotrigine | Document 9746003
6. Drug_Interaction | tenofovir -> vancomycin | Document 19642243
7. Negative_Correlation | terbutaline -> preterm labor | Document 7468724
8. Positive_Correlation | interstitial nephritis -> azithromycin | Document 15602202
9. No_Relation | G246X -> human | Document 18262054

In [13]:
# Stage 5.3E - Save Frozen Few-Shot Demonstrations

FEW_SHOT_SELECTION_PATH = STAGE_5_DIR / "few_shot_selection.pkl"
FEW_SHOT_EXAMPLES_PATH = STAGE_5_DIR / "few_shot_examples.pkl"

with open(FEW_SHOT_SELECTION_PATH, "wb") as f:
    pickle.dump(FEW_SHOT_SELECTION, f)

with open(FEW_SHOT_EXAMPLES_PATH, "wb") as f:
    pickle.dump(few_shot_examples, f)

print("Saved few-shot selection to:")
print(FEW_SHOT_SELECTION_PATH)

print("\nSaved few-shot examples to:")
print(FEW_SHOT_EXAMPLES_PATH)

print("\nNumber of saved examples:", len(few_shot_examples))

Saved few-shot selection to:
/content/drive/MyDrive/Capstone_Project/Stage_5_LLM_RE/few_shot_selection.pkl

Saved few-shot examples to:
/content/drive/MyDrive/Capstone_Project/Stage_5_LLM_RE/few_shot_examples.pkl

Number of saved examples: 9

In [14]:
# Stage 5.4A - Create Reusable Relation Example Formatter

def format_relation_example(example, include_answer=False):
    """
    Format one BioRED relation example for the LLM prompt.

    Entity 1 is marked using @...$ markers.
    Entity 2 is marked using #...$ markers.

    Args:
        example: BioRED relation example dictionary.
        include_answer: Whether to include the gold relation label.

    Returns:
        Formatted string.
    """

    formatted = (
        f"Document:\n"
        f"{example['marked_text']}\n\n"
        f"Entity 1: {example['entity1_text']}\n"
        f"Entity 1 type: {example['entity1_type']}\n"
        f"Entity 2: {example['entity2_text']}\n"
        f"Entity 2 type: {example['entity2_type']}"
    )

    if include_answer:
        formatted += (
            f'\n\nOutput:\n'
            f'{{"relation": "{example["relation_label"]}"}}'
        )

    return formatted

In [16]:
print(
    format_relation_example(
        few_shot_examples[0],
        include_answer=True
    )
)

Document:
@DiseaseOrPhenotypicFeature$ Cardiovascular complications @/DiseaseOrPhenotypicFeature$ associated with #ChemicalEntity$ terbutaline #/ChemicalEntity$ treatment for preterm labor. Severe cardiovascular complications occurred in eight of 160 patients treated with terbutaline for preterm labor. Associated corticosteroid therapy and twin gestations appear to be predisposing factors. Potential mechanisms of the pathophysiology are briefly discussed.

Entity 1: Cardiovascular complications
Entity 1 type: DiseaseOrPhenotypicFeature
Entity 2: terbutaline
Entity 2 type: ChemicalEntity

Output:
{"relation": "Association"}

In [51]:
# Stage 5.4B - Define Fixed Relation Extraction Instructions

RELATION_INSTRUCTIONS = f"""
You are performing biomedical relation extraction on BioRED data.

Your task is to classify the relationship between Entity 1 and Entity 2.

The document contains special markers:
- Entity 1 is marked using @...$ and @/...$
- Entity 2 is marked using #...$ and #/...$

You MUST choose exactly one relation label from this closed label set:

{", ".join(RELATION_LABELS)}

Rules:
1. Predict only the relationship between the specified Entity 1 and Entity 2.
2. Use the biomedical context in the document.
3. Do not predict relationships involving other entities.
4. You must use ONLY one of the labels listed above.
5. Do not invent alternative labels such as Cause, Causes, Causal, Related_To, Interaction, or None.
6. If the relationship is causal or indicates increased occurrence/risk, map it to the most appropriate BioRED label from the allowed set.
7. If no annotated relationship exists between Entity 1 and Entity 2, return No_Relation.
8. Output valid JSON only.
9. Do not include explanations, reasoning, Markdown, or additional text.

Required output format:
{{"relation": "<one allowed BioRED relation label>"}}
""".strip()

In [17]:
# Stage 5.4C - Build Complete Few-Shot Relation Extraction Prompt

def build_relation_prompt(example, few_shot_examples, instructions):
    """
    Build the complete few-shot relation extraction prompt.

    Args:
        example: Target BioRED relation example to classify.
        few_shot_examples: Frozen few-shot demonstration examples.
        instructions: Fixed relation extraction instruction block.

    Returns:
        Complete prompt string.
    """

    prompt_parts = [instructions]

    prompt_parts.append(
        "\n\nFew-shot examples:"
    )

    for i, demo in enumerate(few_shot_examples, start=1):

        formatted_demo = format_relation_example(
            demo,
            include_answer=True
        )

        prompt_parts.append(
            f"\n\nExample {i}\n"
            f"{formatted_demo}"
        )

    target_example = format_relation_example(
        example,
        include_answer=False
    )

    prompt_parts.append(
        "\n\nNow classify the following example:\n"
        f"{target_example}\n\n"
        "Output:"
    )

    return "".join(prompt_parts)

In [18]:
# Find one non-demonstration training example for prompt testing

few_shot_keys = {
    (
        example["document_id"],
        example["entity1_annotation_id"],
        example["entity2_annotation_id"],
        example["relation_label"]
    )
    for example in few_shot_examples
}

prompt_test_example = next(
    example
    for example in relation_data["train"]
    if (
        example["document_id"],
        example["entity1_annotation_id"],
        example["entity2_annotation_id"],
        example["relation_label"]
    ) not in few_shot_keys
)

test_prompt = build_relation_prompt(
    prompt_test_example,
    few_shot_examples,
    RELATION_INSTRUCTIONS
)

print(test_prompt)

You are performing biomedical relation extraction on BioRED data.

Your task is to classify the relationship between Entity 1 and Entity 2.

The document contains special markers:
- Entity 1 is marked using @...$ and @/...$
- Entity 2 is marked using #...$ and #/...$

Choose exactly one relation label from the following list:

Association, Bind, Comparison, Conversion, Cotreatment, Drug_Interaction, Negative_Correlation, Positive_Correlation, No_Relation

Rules:
1. Predict only the relationship between the specified Entity 1 and Entity 2.
2. Use the biomedical context in the document.
3. Do not predict relationships involving other entities.
4. Return exactly one valid relation label.
5. If no annotated relationship exists between Entity 1 and Entity 2, return No_Relation.
6. Output valid JSON only.
7. Do not include explanations, reasoning, Markdown, or additional text.

Required output format:
{"relation": "<relation_label>"}

Few-shot examples:

Example 1
Document:
@DiseaseOrPhenotypicFeature$ Cardiovascular complications @/DiseaseOrPhenotypicFeature$ associated with #ChemicalEntity$ terbutaline #/ChemicalEntity$ treatment for preterm labor. Severe cardiovascular complications occurred in eight of 160 patients treated with terbutaline for preterm labor. Associated corticosteroid therapy and twin gestations appear to be predisposing factors. Potential mechanisms of the pathophysiology are briefly discussed.

Entity 1: Cardiovascular complications
Entity 1 type: DiseaseOrPhenotypicFeature
Entity 2: terbutaline
Entity 2 type: ChemicalEntity

Output:
{"relation": "Association"}

Example 2
Document:
@GeneOrGeneProduct$ Langerin @/GeneOrGeneProduct$, a novel C-type lectin specific to Langerhans cells, is an endocytic receptor that induces the formation of Birbeck granules. We have identified a type II Ca2+-dependent lectin displaying #ChemicalEntity$ mannose #/ChemicalEntity$-binding specificity, exclusively expressed by Langerhans cells (LC), and named Langerin. LC are uniquely characterized by Birbeck granules (BG), which are organelles consisting of superimposed and zippered membranes. Here, we have shown that Langerin is constitutively associated with BG and that antibody to Langerin is internalized into these structures. Remarkably, transfection of Langerin cDNA into fibroblasts created a compact network of membrane structures with typical features of BG. Langerin is thus a potent inducer of membrane superimposition and zippering leading to BG formation. Our data suggest that induction of BG is a consequence of the antigen-capture function of Langerin, allowing routing into these organelles and providing access to a nonclassical antigen-processing pathway.

Entity 1: Langerin
Entity 1 type: GeneOrGeneProduct
Entity 2: mannose
Entity 2 type: ChemicalEntity

Output:
{"relation": "Bind"}

Example 3
Document:
Anticonvulsant effect of eslicarbazepine acetate (BIA 2-093) on seizures induced by microperfusion of picrotoxin in the hippocampus of freely moving rats. Eslicarbazepine acetate (BIA 2-093, S-(-)-10-acetoxy-10,11-dihydro-5H-dibenzo/b,f/azepine-5-carboxamide) is a novel antiepileptic drug, now in Phase III clinical trials, designed with the aim of improving efficacy and safety in comparison with the structurally related drugs @ChemicalEntity$ carbamazepine @/ChemicalEntity$ (CBZ) and #ChemicalEntity$ oxcarbazepine #/ChemicalEntity$ (OXC). We have studied the effects of oral treatment with eslicarbazepine acetate on a whole-animal model in which partial seizures can be elicited repeatedly on different days without changes in threshold or seizure patterns. In the animals treated with threshold doses of picrotoxin, the average number of seizures was 2.3+/-1.2, and average seizure duration was 39.5+/-8.4s. Pre-treatment with a dose of 30 mg/kg 2h before picrotoxin microperfusion prevented seizures in the 75% of the rats. Lower doses (3 and 10mg/kg) did not suppress seizures, however, after administration of 10mg/kg, significant reductions in seizures duration (24.3+/-6.8s) and seizure number (1.6+/-0.34) were found. No adverse effects of eslicarbazepine acetate were observed in the behavioral/EEG patterns studied, including sleep/wakefulness cycle, at the doses studied.

Entity 1: carbamazepine
Entity 1 type: ChemicalEntity
Entity 2: oxcarbazepine
Entity 2 type: ChemicalEntity

Output:
{"relation": "Comparison"}

Example 4
Document:
The phosphatidylethanolamine N-methyltransferase gene V175M single nucleotide polymorphism confers the susceptibility to NASH in Japanese population. BACKGROUND/AIMS: The genetic predisposition on the development of nonalcoholic steatohepatitis (NASH) has been poorly understood. A functional polymorphism Val175Met was reported in phosphatidylethanolamine N-methyltransferase (PEMT) that catalyzes the conversion of @ChemicalEntity$ phosphatidylethanolamine @/ChemicalEntity$ to #ChemicalEntity$ phosphatidylcholine #/ChemicalEntity$. The aim of this study was to investigate whether the carriers of Val175Met variant impaired in PEMT activity are more susceptible to NASH. METHODS: Blood samples of 107 patients with biopsy-proven NASH and of 150 healthy volunteers were analyzed by the polymerase chain reaction (PCR) and restriction fragment length polymorphism. RESULTS: Val175Met variant allele of the PEMT gene was significantly more frequent in NASH patients than in healthy volunteers (p<0.001), and carriers of Val175Met variant were significantly more frequent in NASH patients than in healthy volunteers (p<0.01). Among NASH patients, body mass index was significantly lower (p<0.05), and non-obese patients were significantly more frequent (p<0.001) in carriers of Val175Met variant than in homozygotes of wild type PEMT. CONCLUSIONS: Val175Met variant of PEMT could be a candidate molecule that determines the susceptibility to NASH, because it is more frequently observed in NASH patients and non-obese persons with Val175Met variant of PEMT are facilitated to develop NASH.

Entity 1: phosphatidylethanolamine
Entity 1 type: ChemicalEntity
Entity 2: phosphatidylcholine
Entity 2 type: ChemicalEntity

Output:
{"relation": "Conversion"}

Example 5
Document:
Inappropriate use of carbamazepine and vigabatrin in typical absence seizures. Carbamazepine and vigabatrin are contraindicated in typical absence seizures. Of 18 consecutive referrals of children with resistant typical absences only, eight were erroneously treated with carbamazepine either as monotherapy or as an add-on. Vigabatrin was also used in the treatment of two children. Frequency of absences increased in four children treated with carbamazepine and two of these developed myoclonic jerks, which resolved on withdrawal of carbamazepine. Absences were aggravated in both cases where vigabatrin was added on to concurrent treatment. Optimal control of the absences was achieved with @ChemicalEntity$ sodium valproate @/ChemicalEntity$, #ChemicalEntity$ lamotrigine #/ChemicalEntity$, or ethosuximide alone or in combination.

Entity 1: sodium valproate
Entity 1 type: ChemicalEntity
Entity 2: lamotrigine
Entity 2 type: ChemicalEntity

Output:
{"relation": "Cotreatment"}

Example 6
Document:
Acute renal failure in patients with AIDS on @ChemicalEntity$ tenofovir @/ChemicalEntity$ while receiving prolonged #ChemicalEntity$ vancomycin #/ChemicalEntity$ course for osteomyelitis. Renal failure developed after a prolonged course of vancomycin therapy in 2 patients who were receiving tenofovir disoproxil fumarate as part of an antiretroviral regimen. Tenofovir has been implicated in the development of Fanconi syndrome and renal insufficiency because of its effects on the proximal renal tubule. Vancomycin nephrotoxicity is infrequent but may result from coadministration with a nephrotoxic agent. Clinicians should be aware that tenofovir may raise the risk of renal failure during prolonged administration of vancomycin.

Entity 1: tenofovir
Entity 1 type: ChemicalEntity
Entity 2: vancomycin
Entity 2 type: ChemicalEntity

Output:
{"relation": "Drug_Interaction"}

Example 7
Document:
Cardiovascular complications associated with @ChemicalEntity$ terbutaline @/ChemicalEntity$ treatment for #DiseaseOrPhenotypicFeature$ preterm labor #/DiseaseOrPhenotypicFeature$. Severe cardiovascular complications occurred in eight of 160 patients treated with terbutaline for preterm labor. Associated corticosteroid therapy and twin gestations appear to be predisposing factors. Potential mechanisms of the pathophysiology are briefly discussed.

Entity 1: terbutaline
Entity 1 type: ChemicalEntity
Entity 2: preterm labor
Entity 2 type: DiseaseOrPhenotypicFeature

Output:
{"relation": "Negative_Correlation"}

Example 8
Document:
Recurrent acute @DiseaseOrPhenotypicFeature$ interstitial nephritis @/DiseaseOrPhenotypicFeature$ induced by #ChemicalEntity$ azithromycin #/ChemicalEntity$. A 14-year-old girl is reported with recurrent, azithromycin-induced, acute interstitial nephritis. The second episode was more severe than the first; and although both were treated with intensive corticosteroid therapy, renal function remained impaired. Although most cases of antibiotic induced acute interstitial nephritis are benign and self-limited, some patients are at risk for permanent renal injury.

Entity 1: interstitial nephritis
Entity 1 type: DiseaseOrPhenotypicFeature
Entity 2: azithromycin
Entity 2 type: ChemicalEntity

Output:
{"relation": "Positive_Correlation"}

Example 9
Document:
A family with two consecutive nonsense mutations in BMPR1A causing juvenile polyposis. We describe a novel germline mutation of BMPR1A in a family with juvenile polyposis and colon cancer. This mutation consists of two consecutive substitutions (735-6 TG>AT) that cause two nonsense mutations (Y245X, @SequenceVariant$ G246X @/SequenceVariant$), inherited in an autosomal dominant fashion, on one parental chromosome. This mutation caused protein truncation, and represents a novel case of consecutive nonsense mutations in #OrganismTaxon$ human #/OrganismTaxon$ disease.

Entity 1: G246X
Entity 1 type: SequenceVariant
Entity 2: human
Entity 2 type: OrganismTaxon

Output:
{"relation": "No_Relation"}

Now classify the following example:
Document:
Mechanisms Underlying Latent Disease Risk Associated with Early-Life Arsenic Exposure: Current Research Trends and Scientific Gaps. BACKGROUND: Millions of individuals worldwide, particularly those living in rural and developing areas, are exposed to harmful levels of @ChemicalEntity$ inorganic arsenic @/ChemicalEntity$ (iAs) in their drinking water. Inorganic As exposure during key developmental periods is associated with a variety of adverse health effects including those that are evident in adulthood. There is considerable interest in identifying the molecular mechanisms that relate early-life iAs exposure to the development of these latent diseases, particularly in relationship to #DiseaseOrPhenotypicFeature$ cancer #/DiseaseOrPhenotypicFeature$. OBJECTIVES: This work summarizes research on the molecular mechanisms that underlie the increased risk of cancer development in adulthood that is associated with early-life iAs exposure. DISCUSSION: Epigenetic reprogramming that imparts functional changes in gene expression, the development of cancer stem cells, and immunomodulation are plausible underlying mechanisms by which early-life iAs exposure elicits latent carcinogenic effects. CONCLUSIONS: Evidence is mounting that relates early-life iAs exposure and cancer development later in life. Future research should include animal studies that address mechanistic hypotheses and studies of human populations that integrate early-life exposure, molecular alterations, and latent disease outcomes.

Entity 1: inorganic arsenic
Entity 1 type: ChemicalEntity
Entity 2: cancer
Entity 2 type: DiseaseOrPhenotypicFeature

Output:

In [25]:
# Stage 5.4D - Inspect Few-Shot Prompt Size

prompt_character_count = len(test_prompt)
prompt_word_count = len(test_prompt.split())

print("Prompt characters:", prompt_character_count)
print("Approximate prompt words:", prompt_word_count)

print("\nFew-shot demonstrations:", len(few_shot_examples))
print("Target document ID:", prompt_test_example["document_id"])

Prompt characters: 11877
Approximate prompt words: 1514

Few-shot demonstrations: 9
Target document ID: 26115410

In [19]:
# Stage 5.5A - Install Required Libraries

!pip install -q transformers accelerate bitsandbytes

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.9/40.9 MB 66.8 MB/s eta 0:00:00

In [20]:
# Stage 5.5B - Import Model Libraries and Define Model Configuration

import torch

from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig
)

MODEL_NAME = "Qwen/Qwen2.5-7B-Instruct"

quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True
)

print("Model:", MODEL_NAME)
print("4-bit quantization configured.")
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

Model: Qwen/Qwen2.5-7B-Instruct
4-bit quantization configured.
CUDA available: True
GPU: NVIDIA L4

In [21]:
# Stage 5.5C - Load Qwen Tokenizer and 4-Bit Model

tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME,
    trust_remote_code=True
)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=quantization_config,
    device_map="auto",
    trust_remote_code=True
)

model.eval()

print("Tokenizer loaded.")
print("Model loaded.")
print("Model device:", model.device)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/663 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/27.8k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/339 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/243 [00:00<?, ?B/s]

Tokenizer loaded.
Model loaded.
Model device: cuda:0

In [29]:
print("\nTokenizer vocabulary size:", len(tokenizer))
print("Model dtype:", model.dtype)

Tokenizer vocabulary size: 151665
Model dtype: torch.bfloat16

In [30]:
# Stage 5.5D - Measure Exact Prompt Token Length

prompt_tokens = tokenizer(
    test_prompt,
    add_special_tokens=False,
    return_tensors=None
)["input_ids"]

prompt_token_count = len(prompt_tokens)

print("Exact prompt token count:", prompt_token_count)

print(
    "Model maximum context length:",
    tokenizer.model_max_length
)

Exact prompt token count: 2840
Model maximum context length: 131072

In [31]:
context_usage_percent = (
    prompt_token_count / tokenizer.model_max_length
) * 100

print(
    f"Approximate context usage: "
    f"{context_usage_percent:.2f}%"
)

Approximate context usage: 2.17%

In [22]:
# Stage 5.5E - Create Reusable Qwen Generation Function

def generate_relation_output(
    prompt,
    max_new_tokens=64
):
    """
    Generate a relation extraction response using Qwen2.5-7B-Instruct.

    Args:
        prompt: Complete few-shot relation extraction prompt.
        max_new_tokens: Maximum number of tokens to generate.

    Returns:
        Raw generated text.
    """

    messages = [
        {
            "role": "user",
            "content": prompt
        }
    ]

    formatted_prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(
        formatted_prompt,
        return_tensors="pt"
    ).to(model.device)

    with torch.inference_mode():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )

    generated_tokens = outputs[
        0,
        inputs["input_ids"].shape[1]:
    ]

    raw_output = tokenizer.decode(
        generated_tokens,
        skip_special_tokens=True
    ).strip()

    return raw_output

In [33]:
# Stage 5.5F - Test Single Relation Extraction Generation

raw_output = generate_relation_output(
    test_prompt
)

print("Raw model output:")
print(raw_output)

print("\nGold relation:")
print(prompt_test_example["relation_label"])

Raw model output:
{"relation": "Positive_Correlation"}

Gold relation:
Positive_Correlation

In [34]:
# Stage 5.5G - Process and Validate Single Model Prediction

processed_output = process_relation_output(raw_output)

print("Raw output:")
print(raw_output)

print("\nProcessed output:")
print(processed_output)

print("\nGold relation:")
print(prompt_test_example["relation_label"])

print(
    "\nPrediction correct:",
    processed_output["relation"] == prompt_test_example["relation_label"]
)

Raw output:
{"relation": "Positive_Correlation"}

Processed output:
{'valid_json': True, 'valid_relation': True, 'relation': 'Positive_Correlation', 'error': None}

Gold relation:
Positive_Correlation

Prediction correct: True

In [23]:
# Stage 5.6A - Create Complete Single-Example Relation Inference Function

def run_relation_inference(example):
    """
    Run the complete Stage 5 relation extraction pipeline
    for one BioRED relation example.

    Returns:
        Dictionary containing prediction details.
    """

    prompt = build_relation_prompt(
        example,
        few_shot_examples,
        RELATION_INSTRUCTIONS
    )

    raw_output = generate_relation_output(prompt)

    processed_output = process_relation_output(raw_output)

    result = {
        "document_id": example["document_id"],
        "entity1_text": example["entity1_text"],
        "entity1_type": example["entity1_type"],
        "entity2_text": example["entity2_text"],
        "entity2_type": example["entity2_type"],
        "gold_relation": example["relation_label"],
        "predicted_relation": processed_output["relation"],
        "valid_json": processed_output["valid_json"],
        "valid_relation": processed_output["valid_relation"],
        "raw_output": raw_output,
        "error": processed_output["error"]
    }

    return result

In [24]:
single_result = run_relation_inference(
    prompt_test_example
)

for key, value in single_result.items():
    print(f"{key}: {value}")

document_id: 26115410
entity1_text: inorganic arsenic
entity1_type: ChemicalEntity
entity2_text: cancer
entity2_type: DiseaseOrPhenotypicFeature
gold_relation: Positive_Correlation
predicted_relation: Positive_Correlation
valid_json: True
valid_relation: True
raw_output: {"relation": "Positive_Correlation"}
error: None

In [25]:
# Stage 5.6B - Define Development Checkpoint and Resume Paths

DEV_CHECKPOINT_PATH = STAGE_5_DIR / "development_predictions_checkpoint.pkl"
DEV_FINAL_PATH = STAGE_5_DIR / "development_predictions_final.pkl"

print("Development checkpoint path:")
print(DEV_CHECKPOINT_PATH)

print("\nDevelopment final results path:")
print(DEV_FINAL_PATH)

def load_existing_predictions(checkpoint_path):
    """
    Load existing predictions if a checkpoint exists.
    Otherwise return an empty list.
    """

    if checkpoint_path.exists():
        with open(checkpoint_path, "rb") as f:
            predictions = pickle.load(f)

        print(
            f"Existing checkpoint found: "
            f"{len(predictions)} predictions loaded."
        )

        return predictions

    print("No existing checkpoint found.")
    return []

Development checkpoint path:
/content/drive/MyDrive/Capstone_Project/Stage_5_LLM_RE/development_predictions_checkpoint.pkl

Development final results path:
/content/drive/MyDrive/Capstone_Project/Stage_5_LLM_RE/development_predictions_final.pkl

In [36]:
development_predictions = load_existing_predictions(
    DEV_CHECKPOINT_PATH
)

print(
    "\nPredictions currently available:",
    len(development_predictions)
)

No existing checkpoint found.

Predictions currently available: 0

In [27]:
# Stage 5.6C - Create Resumable Development Inference Loop

def run_development_inference(
    examples,
    checkpoint_path,
    existing_predictions=None,
    max_examples=None,
    checkpoint_every=5
):
    """
    Run resumable relation extraction inference on development examples.

    Args:
        examples: Development examples.
        checkpoint_path: Path used to save intermediate predictions.
        existing_predictions: Previously completed predictions, if any.
        max_examples: Optional limit for testing.
        checkpoint_every: Save checkpoint after this many new predictions.

    Returns:
        List of prediction dictionaries.
    """

    predictions = (
        list(existing_predictions)
        if existing_predictions is not None
        else []
    )

    start_index = len(predictions)

    if max_examples is None:
        end_index = len(examples)
    else:
        end_index = min(start_index + max_examples, len(examples))

    print(f"Starting from example index: {start_index}")
    print(f"Stopping at example index: {end_index}")
    print(f"Already completed: {len(predictions)}")

    for index in range(start_index, end_index):

        example = examples[index]

        try:
            result = run_relation_inference(example)

        except Exception as error:
            result = {
                "document_id": example["document_id"],
                "entity1_text": example["entity1_text"],
                "entity1_type": example["entity1_type"],
                "entity2_text": example["entity2_text"],
                "entity2_type": example["entity2_type"],
                "gold_relation": example["relation_label"],
                "predicted_relation": None,
                "valid_json": False,
                "valid_relation": False,
                "raw_output": None,
                "error": str(error)
            }

        predictions.append(result)

        completed = len(predictions)

        print(
            f"{completed}/{len(examples)} | "
            f"Gold: {result['gold_relation']} | "
            f"Predicted: {result['predicted_relation']}"
        )

        if completed % checkpoint_every == 0:
            with open(checkpoint_path, "wb") as f:
                pickle.dump(predictions, f)

            print(f"Checkpoint saved at {completed} predictions.")

    # Save once more at the end
    with open(checkpoint_path, "wb") as f:
        pickle.dump(predictions, f)

    print("\nInference batch complete.")
    print("Total predictions saved:", len(predictions))

    return predictions

In [35]:
# Stage 5.6F - Reset Development Checkpoint After Prompt Update

if DEV_CHECKPOINT_PATH.exists():
    DEV_CHECKPOINT_PATH.unlink()
    print("Old development checkpoint deleted.")
else:
    print("No checkpoint found.")

development_predictions = []

Old development checkpoint deleted.

In [37]:
development_predictions = run_development_inference(
    examples=relation_data["development"],
    checkpoint_path=DEV_CHECKPOINT_PATH,
    existing_predictions=development_predictions,
    max_examples=5,
    checkpoint_every=5
)

Starting from example index: 0
Stopping at example index: 5
Already completed: 0
1/2324 | Gold: Positive_Correlation | Predicted: Association
2/2324 | Gold: Association | Predicted: Negative_Correlation
3/2324 | Gold: Positive_Correlation | Predicted: Association
4/2324 | Gold: Positive_Correlation | Predicted: Association
5/2324 | Gold: Association | Predicted: Association
Checkpoint saved at 5 predictions.

Inference batch complete.
Total predictions saved: 5

In [38]:
# Stage 5.6G - Verify Development Checkpoint Resume

reloaded_development_predictions = load_existing_predictions(
    DEV_CHECKPOINT_PATH
)

print(
    "\nReloaded prediction count:",
    len(reloaded_development_predictions)
)

if len(reloaded_development_predictions) == 5:
    print("Checkpoint resume verification successful.")
else:
    print("Unexpected checkpoint size.")

Existing checkpoint found: 5 predictions loaded.

Reloaded prediction count: 5
Checkpoint resume verification successful.

In [39]:
# Stage 5.6H - Run Full Development Inference with Checkpointing

development_predictions = run_development_inference(
    examples=relation_data["development"],
    checkpoint_path=DEV_CHECKPOINT_PATH,
    existing_predictions=reloaded_development_predictions,
    max_examples=None,
    checkpoint_every=25
)

Starting from example index: 5
Stopping at example index: 2324
Already completed: 5
6/2324 | Gold: Negative_Correlation | Predicted: Association
7/2324 | Gold: Negative_Correlation | Predicted: None
8/2324 | Gold: Negative_Correlation | Predicted: No_Relation
9/2324 | Gold: Association | Predicted: Bind
10/2324 | Gold: Negative_Correlation | Predicted: Negative_Correlation
11/2324 | Gold: Positive_Correlation | Predicted: Association
12/2324 | Gold: Association | Predicted: Association
13/2324 | Gold: Positive_Correlation | Predicted: Positive_Correlation
14/2324 | Gold: Association | Predicted: Positive_Correlation
15/2324 | Gold: Association | Predicted: Positive_Correlation
16/2324 | Gold: Association | Predicted: No_Relation
17/2324 | Gold: Association | Predicted: Positive_Correlation
18/2324 | Gold: Association | Predicted: Positive_Correlation
19/2324 | Gold: Association | Predicted: Positive_Correlation
20/2324 | Gold: Association | Predicted: Positive_Correlation
21/2324 | Gold: Association | Predicted: Positive_Correlation
22/2324 | Gold: Association | Predicted: Positive_Correlation
23/2324 | Gold: Association | Predicted: Positive_Correlation
24/2324 | Gold: Association | Predicted: Positive_Correlation
25/2324 | Gold: Association | Predicted: Association
Checkpoint saved at 25 predictions.
26/2324 | Gold: Association | Predicted: Association
27/2324 | Gold: Positive_Correlation | Predicted: Association
28/2324 | Gold: Positive_Correlation | Predicted: Association
29/2324 | Gold: Positive_Correlation | Predicted: No_Relation
30/2324 | Gold: Association | Predicted: Association
31/2324 | Gold: Negative_Correlation | Predicted: Association
32/2324 | Gold: Positive_Correlation | Predicted: No_Relation
33/2324 | Gold: Positive_Correlation | Predicted: No_Relation
34/2324 | Gold: Association | Predicted: No_Relation
35/2324 | Gold: Association | Predicted: Negative_Correlation
36/2324 | Gold: Negative_Correlation | Predicted: Association
37/2324 | Gold: Association | Predicted: Association
38/2324 | Gold: Positive_Correlation | Predicted: Positive_Correlation
39/2324 | Gold: Positive_Correlation | Predicted: Association
40/2324 | Gold: Bind | Predicted: Bind
41/2324 | Gold: Association | Predicted: Association
42/2324 | Gold: Positive_Correlation | Predicted: No_Relation
43/2324 | Gold: Positive_Correlation | Predicted: Association
44/2324 | Gold: Association | Predicted: Association
45/2324 | Gold: Positive_Correlation | Predicted: Association
46/2324 | Gold: Association | Predicted: Negative_Correlation
47/2324 | Gold: Bind | Predicted: Bind
48/2324 | Gold: Association | Predicted: Positive_Correlation
49/2324 | Gold: Association | Predicted: Bind
50/2324 | Gold: Association | Predicted: Positive_Correlation
Checkpoint saved at 50 predictions.
51/2324 | Gold: Association | Predicted: Positive_Correlation
52/2324 | Gold: Association | Predicted: Positive_Correlation
53/2324 | Gold: Positive_Correlation | Predicted: Positive_Correlation
54/2324 | Gold: Association | Predicted: Negative_Correlation
55/2324 | Gold: Association | Predicted: Negative_Correlation
56/2324 | Gold: Association | Predicted: Negative_Correlation
57/2324 | Gold: Association | Predicted: Association
58/2324 | Gold: Association | Predicted: Positive_Correlation
59/2324 | Gold: Association | Predicted: No_Relation
60/2324 | Gold: Association | Predicted: No_Relation
61/2324 | Gold: Association | Predicted: None
62/2324 | Gold: Association | Predicted: Association
63/2324 | Gold: Association | Predicted: No_Relation
64/2324 | Gold: Negative_Correlation | Predicted: No_Relation
65/2324 | Gold: Association | Predicted: No_Relation
66/2324 | Gold: Positive_Correlation | Predicted: No_Relation
67/2324 | Gold: Association | Predicted: No_Relation
68/2324 | Gold: Association | Predicted: Association
69/2324 | Gold: Positive_Correlation | Predicted: No_Relation
70/2324 | Gold: Positive_Correlation | Predicted: Association
71/2324 | Gold: Negative_Correlation | Predicted: Positive_Correlation
72/2324 | Gold: Association | Predicted: Bind
73/2324 | Gold: Association | Predicted: Bind
74/2324 | Gold: Association | Predicted: Bind
75/2324 | Gold: Negative_Correlation | Predicted: No_Relation
Checkpoint saved at 75 predictions.
76/2324 | Gold: Negative_Correlation | Predicted: No_Relation
77/2324 | Gold: Negative_Correlation | Predicted: Association
78/2324 | Gold: Negative_Correlation | Predicted: No_Relation
79/2324 | Gold: Negative_Correlation | Predicted: No_Relation
80/2324 | Gold: Negative_Correlation | Predicted: No_Relation
81/2324 | Gold: Association | Predicted: No_Relation
82/2324 | Gold: Negative_Correlation | Predicted: No_Relation
83/2324 | Gold: Negative_Correlation | Predicted: No_Relation
84/2324 | Gold: Positive_Correlation | Predicted: Association
85/2324 | Gold: Positive_Correlation | Predicted: Association
86/2324 | Gold: Positive_Correlation | Predicted: Negative_Correlation
87/2324 | Gold: Association | Predicted: Association
88/2324 | Gold: Bind | Predicted: Association
89/2324 | Gold: Bind | Predicted: Association
90/2324 | Gold: Bind | Predicted: No_Relation
91/2324 | Gold: Positive_Correlation | Predicted: Positive_Correlation
92/2324 | Gold: Association | Predicted: Association
93/2324 | Gold: Positive_Correlation | Predicted: Positive_Correlation
94/2324 | Gold: Association | Predicted: Negative_Correlation
95/2324 | Gold: Association | Predicted: No_Relation
96/2324 | Gold: Negative_Correlation | Predicted: Negative_Correlation
97/2324 | Gold: Positive_Correlation | Predicted: Association
98/2324 | Gold: Negative_Correlation | Predicted: Negative_Correlation
99/2324 | Gold: Negative_Correlation | Predicted: Negative_Correlation
100/2324 | Gold: Negative_Correlation | Predicted: Drug_Interaction
Checkpoint saved at 100 predictions.
101/2324 | Gold: Negative_Correlation | Predicted: Negative_Correlation
102/2324 | Gold: Association | Predicted: Association
103/2324 | Gold: Association | Predicted: Association
104/2324 | Gold: Negative_Correlation | Predicted: Association
105/2324 | Gold: Negative_Correlation | Predicted: Negative_Correlation
106/2324 | Gold: Association | Predicted: Association
107/2324 | Gold: Association | Predicted: No_Relation
108/2324 | Gold: Positive_Correlation | Predicted: Association
109/2324 | Gold: Positive_Correlation | Predicted: None
110/2324 | Gold: Positive_Correlation | Predicted: None
111/2324 | Gold: Positive_Correlation | Predicted: None
112/2324 | Gold: Positive_Correlation | Predicted: None
113/2324 | Gold: Negative_Correlation | Predicted: Cotreatment
114/2324 | Gold: Association | Predicted: Association
115/2324 | Gold: Association | Predicted: No_Relation
116/2324 | Gold: Cotreatment | Predicted: Cotreatment
117/2324 | Gold: Positive_Correlation | Predicted: None
118/2324 | Gold: Positive_Correlation | Predicted: Positive_Correlation
119/2324 | Gold: Positive_Correlation | Predicted: Association
120/2324 | Gold: Positive_Correlation | Predicted: No_Relation
121/2324 | Gold: Positive_Correlation | Predicted: Association
122/2324 | Gold: Positive_Correlation | Predicted: Association
123/2324 | Gold: Positive_Correlation | Predicted: Association
124/2324 | Gold: Positive_Correlation | Predicted: No_Relation
125/2324 | Gold: Positive_Correlation | Predicted: No_Relation
Checkpoint saved at 125 predictions.
126/2324 | Gold: Positive_Correlation | Predicted: No_Relation
127/2324 | Gold: Positive_Correlation | Predicted: Association
128/2324 | Gold: Positive_Correlation | Predicted: Association
129/2324 | Gold: Positive_Correlation | Predicted: Association
130/2324 | Gold: Positive_Correlation | Predicted: Association
131/2324 | Gold: Positive_Correlation | Predicted: Association
132/2324 | Gold: Positive_Correlation | Predicted: No_Relation
133/2324 | Gold: Positive_Correlation | Predicted: No_Relation
134/2324 | Gold: Positive_Correlation | Predicted: No_Relation
135/2324 | Gold: Positive_Correlation | Predicted: No_Relation
136/2324 | Gold: Positive_Correlation | Predicted: No_Relation
137/2324 | Gold: Positive_Correlation | Predicted: No_Relation
138/2324 | Gold: Positive_Correlation | Predicted: No_Relation
139/2324 | Gold: Positive_Correlation | Predicted: Association
140/2324 | Gold: Positive_Correlation | Predicted: No_Relation
141/2324 | Gold: Positive_Correlation | Predicted: No_Relation
142/2324 | Gold: Positive_Correlation | Predicted: No_Relation
143/2324 | Gold: Positive_Correlation | Predicted: Association
144/2324 | Gold: Negative_Correlation | Predicted: Association
145/2324 | Gold: Association | Predicted: Association
146/2324 | Gold: Association | Predicted: Association
147/2324 | Gold: Association | Predicted: No_Relation
148/2324 | Gold: Association | Predicted: Association
149/2324 | Gold: Positive_Correlation | Predicted: Association
150/2324 | Gold: Positive_Correlation | Predicted: No_Relation
Checkpoint saved at 150 predictions.
151/2324 | Gold: Association | Predicted: No_Relation
152/2324 | Gold: Association | Predicted: Conversion
153/2324 | Gold: Association | Predicted: No_Relation
154/2324 | Gold: Positive_Correlation | Predicted: Positive_Correlation
155/2324 | Gold: Association | Predicted: Positive_Correlation
156/2324 | Gold: Association | Predicted: Positive_Correlation
157/2324 | Gold: Association | Predicted: Positive_Correlation
158/2324 | Gold: Association | Predicted: Positive_Correlation
159/2324 | Gold: Negative_Correlation | Predicted: No_Relation
160/2324 | Gold: Negative_Correlation | Predicted: No_Relation
161/2324 | Gold: Positive_Correlation | Predicted: Positive_Correlation
162/2324 | Gold: Positive_Correlation | Predicted: Positive_Correlation
163/2324 | Gold: Positive_Correlation | Predicted: Positive_Correlation
164/2324 | Gold: Association | Predicted: Association
165/2324 | Gold: Negative_Correlation | Predicted: Positive_Correlation
166/2324 | Gold: Negative_Correlation | Predicted: Negative_Correlation
167/2324 | Gold: Positive_Correlation | Predicted: Association
168/2324 | Gold: Association | Predicted: No_Relation
169/2324 | Gold: Association | Predicted: No_Relation
170/2324 | Gold: Positive_Correlation | Predicted: No_Relation
171/2324 | Gold: Association | Predicted: No_Relation
172/2324 | Gold: Association | Predicted: No_Relation
173/2324 | Gold: Association | Predicted: No_Relation
174/2324 | Gold: Association | Predicted: Bind
175/2324 | Gold: Association | Predicted: No_Relation
Checkpoint saved at 175 predictions.
176/2324 | Gold: Positive_Correlation | Predicted: Association
177/2324 | Gold: Negative_Correlation | Predicted: No_Relation
178/2324 | Gold: Negative_Correlation | Predicted: None
179/2324 | Gold: Positive_Correlation | Predicted: No_Relation
180/2324 | Gold: Positive_Correlation | Predicted: No_Relation
181/2324 | Gold: Positive_Correlation | Predicted: No_Relation
182/2324 | Gold: Bind | Predicted: Bind
183/2324 | Gold: Bind | Predicted: Conversion
184/2324 | Gold: Negative_Correlation | Predicted: Conversion
185/2324 | Gold: Negative_Correlation | Predicted: Negative_Correlation
186/2324 | Gold: Negative_Correlation | Predicted: Negative_Correlation
187/2324 | Gold: Association | Predicted: Positive_Correlation
188/2324 | Gold: Positive_Correlation | Predicted: Positive_Correlation
189/2324 | Gold: Positive_Correlation | Predicted: Positive_Correlation
190/2324 | Gold: Negative_Correlation | Predicted: Negative_Correlation
191/2324 | Gold: Negative_Correlation | Predicted: No_Relation
192/2324 | Gold: Positive_Correlation | Predicted: Association
193/2324 | Gold: Bind | Predicted: Positive_Correlation
194/2324 | Gold: Negative_Correlation | Predicted: Negative_Correlation
195/2324 | Gold: Positive_Correlation | Predicted: Negative_Correlation
196/2324 | Gold: Negative_Correlation | Predicted: Negative_Correlation
197/2324 | Gold: Association | Predicted: Positive_Correlation
198/2324 | Gold: Association | Predicted: Negative_Correlation
199/2324 | Gold: Negative_Correlation | Predicted: No_Relation
200/2324 | Gold: Negative_Correlation | Predicted: No_Relation
Checkpoint saved at 200 predictions.
201/2324 | Gold: Negative_Correlation | Predicted: Negative_Correlation
202/2324 | Gold: Negative_Correlation | Predicted: Negative_Correlation
203/2324 | Gold: Association | Predicted: No_Relation
204/2324 | Gold: Negative_Correlation | Predicted: Negative_Correlation
205/2324 | Gold: Negative_Correlation | Predicted: Association
206/2324 | Gold: Negative_Correlation | Predicted: No_Relation
207/2324 | Gold: Negative_Correlation | Predicted: Negative_Correlation
208/2324 | Gold: Association | Predicted: No_Relation
209/2324 | Gold: Association | Predicted: No_Relation
210/2324 | Gold: Negative_Correlation | Predicted: Negative_Correlation
211/2324 | Gold: Negative_Correlation | Predicted: Negative_Correlation
212/2324 | Gold: Association | Predicted: No_Relation
213/2324 | Gold: Positive_Correlation | Predicted: Positive_Correlation
214/2324 | Gold: Positive_Correlation | Predicted: Positive_Correlation
215/2324 | Gold: Association | Predicted: Association
216/2324 | Gold: Association | Predicted: Association
217/2324 | Gold: Association | Predicted: No_Relation
218/2324 | Gold: Negative_Correlation | Predicted: No_Relation
219/2324 | Gold: Association | Predicted: No_Relation
220/2324 | Gold: Association | Predicted: No_Relation
221/2324 | Gold: Association | Predicted: No_Relation
222/2324 | Gold: Association | Predicted: No_Relation
223/2324 | Gold: Association | Predicted: No_Relation
224/2324 | Gold: Association | Predicted: No_Relation
225/2324 | Gold: Association | Predicted: No_Relation
Checkpoint saved at 225 predictions.
226/2324 | Gold: Association | Predicted: No_Relation
227/2324 | Gold: Association | Predicted: No_Relation
228/2324 | Gold: Association | Predicted: No_Relation
229/2324 | Gold: Association | Predicted: Association
230/2324 | Gold: Association | Predicted: No_Relation
231/2324 | Gold: Association | Predicted: No_Relation
232/2324 | Gold: Association | Predicted: No_Relation
233/2324 | Gold: Association | Predicted: Association
234/2324 | Gold: Association | Predicted: No_Relation
235/2324 | Gold: Association | Predicted: Association
236/2324 | Gold: Association | Predicted: No_Relation
237/2324 | Gold: Association | Predicted: Association
238/2324 | Gold: Association | Predicted: No_Relation
239/2324 | Gold: Association | Predicted: Association
240/2324 | Gold: Association | Predicted: Positive_Correlation
241/2324 | Gold: Negative_Correlation | Predicted: Negative_Correlation
242/2324 | Gold: Association | Predicted: Association
243/2324 | Gold: Association | Predicted: No_Relation
244/2324 | Gold: Negative_Correlation | Predicted: No_Relation
245/2324 | Gold: Association | Predicted: No_Relation
246/2324 | Gold: Association | Predicted: No_Relation
247/2324 | Gold: Association | Predicted: No_Relation
248/2324 | Gold: Association | Predicted: No_Relation
249/2324 | Gold: Association | Predicted: No_Relation
250/2324 | Gold: Association | Predicted: No_Relation
Checkpoint saved at 250 predictions.
251/2324 | Gold: Association | Predicted: No_Relation
252/2324 | Gold: Association | Predicted: No_Relation
253/2324 | Gold: Association | Predicted: No_Relation
254/2324 | Gold: Association | Predicted: No_Relation
255/2324 | Gold: Association | Predicted: No_Relation
256/2324 | Gold: Association | Predicted: No_Relation
257/2324 | Gold: Association | Predicted: No_Relation
258/2324 | Gold: Association | Predicted: No_Relation
259/2324 | Gold: Association | Predicted: No_Relation
260/2324 | Gold: Association | Predicted: No_Relation
261/2324 | Gold: Association | Predicted: No_Relation
262/2324 | Gold: Association | Predicted: No_Relation
263/2324 | Gold: Association | Predicted: No_Relation
264/2324 | Gold: Association | Predicted: Positive_Correlation
265/2324 | Gold: Negative_Correlation | Predicted: Drug_Interaction
266/2324 | Gold: Association | Predicted: Positive_Correlation
267/2324 | Gold: Association | Predicted: Association
268/2324 | Gold: Positive_Correlation | Predicted: Association
269/2324 | Gold: Association | Predicted: Association
270/2324 | Gold: Association | Predicted: Positive_Correlation
271/2324 | Gold: Negative_Correlation | Predicted: None
272/2324 | Gold: Negative_Correlation | Predicted: None
273/2324 | Gold: Positive_Correlation | Predicted: Positive_Correlation
274/2324 | Gold: Association | Predicted: Association
275/2324 | Gold: Association | Predicted: Association
Checkpoint saved at 275 predictions.
276/2324 | Gold: Association | Predicted: Association
277/2324 | Gold: Association | Predicted: Association
278/2324 | Gold: Association | Predicted: Association
279/2324 | Gold: Association | Predicted: No_Relation
280/2324 | Gold: Association | Predicted: Association
281/2324 | Gold: Association | Predicted: No_Relation
282/2324 | Gold: Negative_Correlation | Predicted: Association
283/2324 | Gold: Association | Predicted: No_Relation
284/2324 | Gold: Negative_Correlation | Predicted: Association
285/2324 | Gold: Association | Predicted: No_Relation
286/2324 | Gold: Negative_Correlation | Predicted: Bind
287/2324 | Gold: Association | Predicted: No_Relation
288/2324 | Gold: Negative_Correlation | Predicted: Bind
289/2324 | Gold: Negative_Correlation | Predicted: Negative_Correlation
290/2324 | Gold: Negative_Correlation | Predicted: Negative_Correlation
291/2324 | Gold: Positive_Correlation | Predicted: Negative_Correlation
292/2324 | Gold: Positive_Correlation | Predicted: Negative_Correlation
293/2324 | Gold: Positive_Correlation | Predicted: Association
294/2324 | Gold: Positive_Correlation | Predicted: Negative_Correlation
295/2324 | Gold: Association | Predicted: Association
296/2324 | Gold: Negative_Correlation | Predicted: Association
297/2324 | Gold: Negative_Correlation | Predicted: No_Relation
298/2324 | Gold: Positive_Correlation | Predicted: No_Relation
299/2324 | Gold: Positive_Correlation | Predicted: Negative_Correlation
300/2324 | Gold: Association | Predicted: Association
Checkpoint saved at 300 predictions.
301/2324 | Gold: Association | Predicted: Association
302/2324 | Gold: Association | Predicted: Positive_Correlation
303/2324 | Gold: Association | Predicted: Positive_Correlation
304/2324 | Gold: Association | Predicted: Association
305/2324 | Gold: Association | Predicted: Positive_Correlation
306/2324 | Gold: Association | Predicted: Positive_Correlation
307/2324 | Gold: Positive_Correlation | Predicted: Positive_Correlation
308/2324 | Gold: Positive_Correlation | Predicted: Positive_Correlation
309/2324 | Gold: Positive_Correlation | Predicted: Positive_Correlation
310/2324 | Gold: Positive_Correlation | Predicted: Positive_Correlation
311/2324 | Gold: Positive_Correlation | Predicted: Positive_Correlation
312/2324 | Gold: Association | Predicted: Association
313/2324 | Gold: Association | Predicted: Association
314/2324 | Gold: Association | Predicted: Association
315/2324 | Gold: Association | Predicted: Association
316/2324 | Gold: Association | Predicted: Association
317/2324 | Gold: Association | Predicted: Association
318/2324 | Gold: Association | Predicted: Association
319/2324 | Gold: Association | Predicted: Association
320/2324 | Gold: Association | Predicted: Association
321/2324 | Gold: Association | Predicted: Association
322/2324 | Gold: Association | Predicted: Association
323/2324 | Gold: Association | Predicted: Association
324/2324 | Gold: Association | Predicted: Association
325/2324 | Gold: Association | Predicted: Association
Checkpoint saved at 325 predictions.
326/2324 | Gold: Association | Predicted: Association
327/2324 | Gold: Association | Predicted: Association
328/2324 | Gold: Association | Predicted: Positive_Correlation
329/2324 | Gold: Positive_Correlation | Predicted: Positive_Correlation
330/2324 | Gold: Association | Predicted: Association

In [40]:
# Stage 5.6I - Save Final Development Predictions

with open(DEV_FINAL_PATH, "wb") as f:
    pickle.dump(development_predictions, f)

print("Final development predictions saved.")
print("Total predictions:", len(development_predictions))
print("Saved to:", DEV_FINAL_PATH)

Final development predictions saved.
Total predictions: 2324
Saved to: /content/drive/MyDrive/Capstone_Project/Stage_5_LLM_RE/development_predictions_final.pkl

In [41]:
# Stage 5.7A - Validate Completed Development Predictions

total_predictions = len(development_predictions)

valid_json_count = sum(
    result["valid_json"]
    for result in development_predictions
)

valid_relation_count = sum(
    result["valid_relation"]
    for result in development_predictions
)

none_prediction_count = sum(
    result["predicted_relation"] is None
    for result in development_predictions
)

print("Total development predictions:", total_predictions)

print(
    "Valid JSON:",
    f"{valid_json_count}/{total_predictions}"
)

print(
    "Valid relation labels:",
    f"{valid_relation_count}/{total_predictions}"
)

print(
    "Invalid / None predictions:",
    none_prediction_count
)

Total development predictions: 2324
Valid JSON: 2324/2324
Valid relation labels: 2300/2324
Invalid / None predictions: 24

In [42]:
# Stage 5.7B - Create Reusable Relation Evaluation Function

from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
    classification_report
)

def evaluate_relation_predictions(predictions):
    """
    Evaluate BioRED relation extraction predictions.
    Invalid/None predictions are counted as incorrect.
    """

    y_true = [
        result["gold_relation"]
        for result in predictions
    ]

    y_pred = [
        result["predicted_relation"]
        if result["predicted_relation"] is not None
        else "__INVALID__"
        for result in predictions
    ]

    accuracy = accuracy_score(y_true, y_pred)

    macro_precision, macro_recall, macro_f1, _ = (
        precision_recall_fscore_support(
            y_true,
            y_pred,
            labels=RELATION_LABELS,
            average="macro",
            zero_division=0
        )
    )

    weighted_precision, weighted_recall, weighted_f1, _ = (
        precision_recall_fscore_support(
            y_true,
            y_pred,
            labels=RELATION_LABELS,
            average="weighted",
            zero_division=0
        )
    )

    print(f"Accuracy: {accuracy:.4f}")

    print("\nMacro Average")
    print(f"Precision: {macro_precision:.4f}")
    print(f"Recall:    {macro_recall:.4f}")
    print(f"F1:        {macro_f1:.4f}")

    print("\nWeighted Average")
    print(f"Precision: {weighted_precision:.4f}")
    print(f"Recall:    {weighted_recall:.4f}")
    print(f"F1:        {weighted_f1:.4f}")

    print("\nPer-Class Results\n")

    print(
        classification_report(
            y_true,
            y_pred,
            labels=RELATION_LABELS,
            digits=4,
            zero_division=0
        )
    )

In [43]:
# Stage 5.7C - Evaluate Development Set

evaluate_relation_predictions(development_predictions)

Accuracy: 0.5000

Macro Average
Precision: 0.2422
Recall:    0.3216
F1:        0.2582

Weighted Average
Precision: 0.5388
Recall:    0.5000
F1:        0.5171

Per-Class Results

                      precision    recall  f1-score   support

         Association     0.3631    0.3554    0.3592       560
                Bind     0.0851    0.2105    0.1212        19
          Comparison     0.1154    0.6000    0.1935         5
          Conversion     0.0000    0.0000    0.0000         0
         Cotreatment     0.2500    0.4000    0.3077        10
    Drug_Interaction     0.0000    0.0000    0.0000         0
Negative_Correlation     0.3140    0.3750    0.3418       216
Positive_Correlation     0.3047    0.2926    0.2986       352
         No_Relation     0.7478    0.6609    0.7017      1162

           micro avg     0.5052    0.5000    0.5026      2324
           macro avg     0.2422    0.3216    0.2582      2324
        weighted avg     0.5388    0.5000    0.5171      2324

In [45]:
# Stage 5.7D - Inspect Development Relation Confusions

from sklearn.metrics import confusion_matrix
import pandas as pd

y_true = [
    result["gold_relation"]
    for result in development_predictions
]

y_pred = [
    result["predicted_relation"]
    if result["predicted_relation"] is not None
    else "__INVALID__"
    for result in development_predictions
]

valid_eval_labels = RELATION_LABELS + ["__INVALID__"]

cm = confusion_matrix(
    y_true,
    y_pred,
    labels=valid_eval_labels
)

confusion_df = pd.DataFrame(
    cm,
    index=valid_eval_labels,
    columns=valid_eval_labels
)

print("Development Confusion Matrix:")
display(confusion_df)

Development Confusion Matrix:

,Association,Bind,Comparison,Conversion,Cotreatment,Drug_Interaction,Negative_Correlation,Positive_Correlation,No_Relation,__INVALID__
Association,199,19,0,6,1,1,60,122,149,3
Bind,12,4,0,1,0,0,0,1,1,0
Comparison,0,0,3,1,0,0,1,0,0,0
Conversion,0,0,0,0,0,0,0,0,0,0
Cotreatment,0,0,0,0,4,2,1,0,3,0
Drug_Interaction,0,0,0,0,0,0,0,0,0,0
Negative_Correlation,38,4,5,1,7,14,81,10,47,9
Positive_Correlation,139,8,0,3,0,2,31,103,59,7
No_Relation,160,12,18,6,4,3,84,102,768,5
__INVALID__,0,0,0,0,0,0,0,0,0,0

In [46]:
# Show Most Common Development Errors

from collections import Counter

error_pairs = Counter(
    (gold, pred)
    for gold, pred in zip(y_true, y_pred)
    if gold != pred
)

print("Most common prediction errors:\n")

for (gold, pred), count in error_pairs.most_common(15):
    print(f"{gold} -> {pred}: {count}")

Most common prediction errors:

No_Relation -> Association: 160
Association -> No_Relation: 149
Positive_Correlation -> Association: 139
Association -> Positive_Correlation: 122
No_Relation -> Positive_Correlation: 102
No_Relation -> Negative_Correlation: 84
Association -> Negative_Correlation: 60
Positive_Correlation -> No_Relation: 59
Negative_Correlation -> No_Relation: 47
Negative_Correlation -> Association: 38
Positive_Correlation -> Negative_Correlation: 31
Association -> Bind: 19
No_Relation -> Comparison: 18
Negative_Correlation -> Drug_Interaction: 14
Bind -> Association: 12

In [52]:
# Stage 5.8A - Save Frozen Final Prompt Configuration

FINAL_PROMPT_CONFIG_PATH = STAGE_5_DIR / "final_prompt_config.pkl"

final_prompt_config = {
    "model_name": MODEL_NAME,
    "relation_labels": RELATION_LABELS,
    "relation_instructions": RELATION_INSTRUCTIONS,
    "few_shot_selection": FEW_SHOT_SELECTION,
    "num_few_shot_examples": len(few_shot_examples),
    "max_new_tokens": 64,
    "do_sample": False
}

with open(FINAL_PROMPT_CONFIG_PATH, "wb") as f:
    pickle.dump(final_prompt_config, f)

print("Final prompt configuration saved.")
print("Saved to:", FINAL_PROMPT_CONFIG_PATH)

Final prompt configuration saved.
Saved to: /content/drive/MyDrive/Capstone_Project/Stage_5_LLM_RE/final_prompt_config.pkl

In [53]:
# Stage 5.9A - Define Test Checkpoint and Resume Paths

TEST_CHECKPOINT_PATH = STAGE_5_DIR / "test_predictions_checkpoint.pkl"
TEST_FINAL_PATH = STAGE_5_DIR / "test_predictions_final.pkl"

print("Test checkpoint path:")
print(TEST_CHECKPOINT_PATH)

print("\nTest final results path:")
print(TEST_FINAL_PATH)

test_predictions = load_existing_predictions(
    TEST_CHECKPOINT_PATH
)

print(
    "\nPredictions currently available:",
    len(test_predictions)
)

Test checkpoint path:
/content/drive/MyDrive/Capstone_Project/Stage_5_LLM_RE/test_predictions_checkpoint.pkl

Test final results path:
/content/drive/MyDrive/Capstone_Project/Stage_5_LLM_RE/test_predictions_final.pkl
No existing checkpoint found.

Predictions currently available: 0

In [54]:
# Stage 5.9B - Run Full Test Inference with Checkpointing

test_predictions = run_development_inference(
    examples=relation_data["test"],
    checkpoint_path=TEST_CHECKPOINT_PATH,
    existing_predictions=test_predictions,
    max_examples=None,
    checkpoint_every=25
)

Starting from example index: 0
Stopping at example index: 2326
Already completed: 0
1/2326 | Gold: Association | Predicted: Association
2/2326 | Gold: Positive_Correlation | Predicted: Association
3/2326 | Gold: Association | Predicted: Association
4/2326 | Gold: Positive_Correlation | Predicted: No_Relation
5/2326 | Gold: Association | Predicted: Association
6/2326 | Gold: Negative_Correlation | Predicted: Association
7/2326 | Gold: Negative_Correlation | Predicted: Negative_Correlation
8/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
9/2326 | Gold: Positive_Correlation | Predicted: Association
10/2326 | Gold: Association | Predicted: Association
11/2326 | Gold: Association | Predicted: Association
12/2326 | Gold: Association | Predicted: Association
13/2326 | Gold: Negative_Correlation | Predicted: Association
14/2326 | Gold: Negative_Correlation | Predicted: Association
15/2326 | Gold: Negative_Correlation | Predicted: None
16/2326 | Gold: Negative_Correlation | Predicted: Negative_Correlation
17/2326 | Gold: Negative_Correlation | Predicted: None
18/2326 | Gold: Negative_Correlation | Predicted: None
19/2326 | Gold: Association | Predicted: Association
20/2326 | Gold: Association | Predicted: Positive_Correlation
21/2326 | Gold: Association | Predicted: Positive_Correlation
22/2326 | Gold: Positive_Correlation | Predicted: Association
23/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
24/2326 | Gold: Association | Predicted: Positive_Correlation
25/2326 | Gold: Association | Predicted: Conversion
Checkpoint saved at 25 predictions.
26/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
27/2326 | Gold: Association | Predicted: Positive_Correlation
28/2326 | Gold: Association | Predicted: Positive_Correlation
29/2326 | Gold: Negative_Correlation | Predicted: Positive_Correlation
30/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
31/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
32/2326 | Gold: Association | Predicted: Positive_Correlation
33/2326 | Gold: Association | Predicted: Conversion
34/2326 | Gold: Association | Predicted: Conversion
35/2326 | Gold: Association | Predicted: Positive_Correlation
36/2326 | Gold: Association | Predicted: Association
37/2326 | Gold: Negative_Correlation | Predicted: Association
38/2326 | Gold: Positive_Correlation | Predicted: None
39/2326 | Gold: Association | Predicted: No_Relation
40/2326 | Gold: Association | Predicted: No_Relation
41/2326 | Gold: Positive_Correlation | Predicted: Drug_Interaction
42/2326 | Gold: Negative_Correlation | Predicted: Positive_Correlation
43/2326 | Gold: Negative_Correlation | Predicted: Bind
44/2326 | Gold: Association | Predicted: Association
45/2326 | Gold: Association | Predicted: Association
46/2326 | Gold: Association | Predicted: Association
47/2326 | Gold: Association | Predicted: Positive_Correlation
48/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
49/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
50/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
Checkpoint saved at 50 predictions.
51/2326 | Gold: Association | Predicted: Positive_Correlation
52/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
53/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
54/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
55/2326 | Gold: Association | Predicted: Positive_Correlation
56/2326 | Gold: Association | Predicted: Positive_Correlation
57/2326 | Gold: Association | Predicted: Positive_Correlation
58/2326 | Gold: Association | Predicted: Positive_Correlation
59/2326 | Gold: Association | Predicted: Association
60/2326 | Gold: Association | Predicted: No_Relation
61/2326 | Gold: Association | Predicted: No_Relation
62/2326 | Gold: Association | Predicted: No_Relation
63/2326 | Gold: Association | Predicted: No_Relation
64/2326 | Gold: Association | Predicted: No_Relation
65/2326 | Gold: Association | Predicted: Positive_Correlation
66/2326 | Gold: Association | Predicted: No_Relation
67/2326 | Gold: Association | Predicted: No_Relation
68/2326 | Gold: Association | Predicted: No_Relation
69/2326 | Gold: Association | Predicted: Positive_Correlation
70/2326 | Gold: Association | Predicted: Positive_Correlation
71/2326 | Gold: Association | Predicted: Positive_Correlation
72/2326 | Gold: Association | Predicted: No_Relation
73/2326 | Gold: Association | Predicted: No_Relation
74/2326 | Gold: Association | Predicted: No_Relation
75/2326 | Gold: Association | Predicted: No_Relation
Checkpoint saved at 75 predictions.
76/2326 | Gold: Association | Predicted: No_Relation
77/2326 | Gold: Association | Predicted: Positive_Correlation
78/2326 | Gold: Association | Predicted: No_Relation
79/2326 | Gold: Association | Predicted: No_Relation
80/2326 | Gold: Association | Predicted: No_Relation
81/2326 | Gold: Association | Predicted: Positive_Correlation
82/2326 | Gold: Association | Predicted: Positive_Correlation
83/2326 | Gold: Association | Predicted: Positive_Correlation
84/2326 | Gold: Negative_Correlation | Predicted: No_Relation
85/2326 | Gold: Negative_Correlation | Predicted: No_Relation
86/2326 | Gold: Association | Predicted: No_Relation
87/2326 | Gold: Association | Predicted: No_Relation
88/2326 | Gold: Association | Predicted: No_Relation
89/2326 | Gold: Association | Predicted: Association
90/2326 | Gold: Association | Predicted: Association
91/2326 | Gold: Association | Predicted: No_Relation
92/2326 | Gold: Association | Predicted: No_Relation
93/2326 | Gold: Association | Predicted: No_Relation
94/2326 | Gold: Association | Predicted: Positive_Correlation
95/2326 | Gold: Association | Predicted: No_Relation
96/2326 | Gold: Association | Predicted: No_Relation
97/2326 | Gold: Association | Predicted: Positive_Correlation
98/2326 | Gold: Association | Predicted: Association
99/2326 | Gold: Negative_Correlation | Predicted: Positive_Correlation
100/2326 | Gold: Negative_Correlation | Predicted: Positive_Correlation
Checkpoint saved at 100 predictions.
101/2326 | Gold: Comparison | Predicted: Cotreatment
102/2326 | Gold: Association | Predicted: No_Relation
103/2326 | Gold: Negative_Correlation | Predicted: Association
104/2326 | Gold: Negative_Correlation | Predicted: Positive_Correlation
105/2326 | Gold: Negative_Correlation | Predicted: Association
106/2326 | Gold: Negative_Correlation | Predicted: Association
107/2326 | Gold: Association | Predicted: Association
108/2326 | Gold: Positive_Correlation | Predicted: Association
109/2326 | Gold: Positive_Correlation | Predicted: Association
110/2326 | Gold: Association | Predicted: Association
111/2326 | Gold: Association | Predicted: No_Relation
112/2326 | Gold: Negative_Correlation | Predicted: Negative_Correlation
113/2326 | Gold: Association | Predicted: Negative_Correlation
114/2326 | Gold: Negative_Correlation | Predicted: Negative_Correlation
115/2326 | Gold: Association | Predicted: No_Relation
116/2326 | Gold: Association | Predicted: Positive_Correlation
117/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
118/2326 | Gold: Negative_Correlation | Predicted: Negative_Correlation
119/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
120/2326 | Gold: Negative_Correlation | Predicted: No_Relation
121/2326 | Gold: Positive_Correlation | Predicted: Negative_Correlation
122/2326 | Gold: Positive_Correlation | Predicted: Negative_Correlation
123/2326 | Gold: Positive_Correlation | Predicted: No_Relation
124/2326 | Gold: Positive_Correlation | Predicted: Association
125/2326 | Gold: Positive_Correlation | Predicted: Association
Checkpoint saved at 125 predictions.
126/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
127/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
128/2326 | Gold: Positive_Correlation | Predicted: No_Relation
129/2326 | Gold: Positive_Correlation | Predicted: Association
130/2326 | Gold: Positive_Correlation | Predicted: No_Relation
131/2326 | Gold: Positive_Correlation | Predicted: No_Relation
132/2326 | Gold: Positive_Correlation | Predicted: No_Relation
133/2326 | Gold: Negative_Correlation | Predicted: Negative_Correlation
134/2326 | Gold: Negative_Correlation | Predicted: Negative_Correlation
135/2326 | Gold: Positive_Correlation | Predicted: Negative_Correlation
136/2326 | Gold: Association | Predicted: Association
137/2326 | Gold: Positive_Correlation | Predicted: Association
138/2326 | Gold: Bind | Predicted: No_Relation
139/2326 | Gold: Bind | Predicted: No_Relation
140/2326 | Gold: Bind | Predicted: No_Relation
141/2326 | Gold: Bind | Predicted: No_Relation
142/2326 | Gold: Positive_Correlation | Predicted: Negative_Correlation
143/2326 | Gold: Positive_Correlation | Predicted: Negative_Correlation
144/2326 | Gold: Negative_Correlation | Predicted: No_Relation
145/2326 | Gold: Negative_Correlation | Predicted: Negative_Correlation
146/2326 | Gold: Negative_Correlation | Predicted: Negative_Correlation
147/2326 | Gold: Negative_Correlation | Predicted: Cotreatment
148/2326 | Gold: Negative_Correlation | Predicted: Association
149/2326 | Gold: Association | Predicted: Positive_Correlation
150/2326 | Gold: Negative_Correlation | Predicted: No_Relation
Checkpoint saved at 150 predictions.
151/2326 | Gold: Negative_Correlation | Predicted: Negative_Correlation
152/2326 | Gold: Positive_Correlation | Predicted: Negative_Correlation
153/2326 | Gold: Negative_Correlation | Predicted: Cotreatment
154/2326 | Gold: Positive_Correlation | Predicted: Negative_Correlation
155/2326 | Gold: Conversion | Predicted: Conversion
156/2326 | Gold: Positive_Correlation | Predicted: Negative_Correlation
157/2326 | Gold: Association | Predicted: No_Relation
158/2326 | Gold: Association | Predicted: Negative_Correlation
159/2326 | Gold: Positive_Correlation | Predicted: No_Relation
160/2326 | Gold: Bind | Predicted: Negative_Correlation
161/2326 | Gold: Positive_Correlation | Predicted: Negative_Correlation
162/2326 | Gold: Negative_Correlation | Predicted: Negative_Correlation
163/2326 | Gold: Association | Predicted: Negative_Correlation
164/2326 | Gold: Negative_Correlation | Predicted: Negative_Correlation
165/2326 | Gold: Negative_Correlation | Predicted: Negative_Correlation
166/2326 | Gold: Negative_Correlation | Predicted: Negative_Correlation
167/2326 | Gold: Association | Predicted: Positive_Correlation
168/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
169/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
170/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
171/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
172/2326 | Gold: Negative_Correlation | Predicted: Negative_Correlation
173/2326 | Gold: Positive_Correlation | Predicted: Negative_Correlation
174/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
175/2326 | Gold: Negative_Correlation | Predicted: Drug_Interaction
Checkpoint saved at 175 predictions.
176/2326 | Gold: Association | Predicted: No_Relation
177/2326 | Gold: Bind | Predicted: Bind
178/2326 | Gold: Association | Predicted: Bind
179/2326 | Gold: Association | Predicted: No_Relation
180/2326 | Gold: Positive_Correlation | Predicted: No_Relation
181/2326 | Gold: Positive_Correlation | Predicted: No_Relation
182/2326 | Gold: Positive_Correlation | Predicted: No_Relation
183/2326 | Gold: Association | Predicted: No_Relation
184/2326 | Gold: Positive_Correlation | Predicted: No_Relation
185/2326 | Gold: Positive_Correlation | Predicted: No_Relation
186/2326 | Gold: Positive_Correlation | Predicted: No_Relation
187/2326 | Gold: Association | Predicted: No_Relation
188/2326 | Gold: Association | Predicted: No_Relation
189/2326 | Gold: Association | Predicted: Association
190/2326 | Gold: Association | Predicted: Association
191/2326 | Gold: Positive_Correlation | Predicted: Bind
192/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
193/2326 | Gold: Positive_Correlation | Predicted: Conversion
194/2326 | Gold: Positive_Correlation | Predicted: Association
195/2326 | Gold: Association | Predicted: Negative_Correlation
196/2326 | Gold: Negative_Correlation | Predicted: Association
197/2326 | Gold: Negative_Correlation | Predicted: Association
198/2326 | Gold: Cotreatment | Predicted: No_Relation
199/2326 | Gold: Association | Predicted: Positive_Correlation
200/2326 | Gold: Association | Predicted: Association
Checkpoint saved at 200 predictions.
201/2326 | Gold: Association | Predicted: Association
202/2326 | Gold: Association | Predicted: Association
203/2326 | Gold: Association | Predicted: Association
204/2326 | Gold: Association | Predicted: No_Relation
205/2326 | Gold: Negative_Correlation | Predicted: Association
206/2326 | Gold: Negative_Correlation | Predicted: Association
207/2326 | Gold: Association | Predicted: Association
208/2326 | Gold: Association | Predicted: Association
209/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
210/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
211/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
212/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
213/2326 | Gold: Association | Predicted: Association
214/2326 | Gold: Association | Predicted: Association
215/2326 | Gold: Association | Predicted: Positive_Correlation
216/2326 | Gold: Association | Predicted: Positive_Correlation
217/2326 | Gold: Association | Predicted: Positive_Correlation
218/2326 | Gold: Association | Predicted: Association
219/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
220/2326 | Gold: Association | Predicted: Association
221/2326 | Gold: Association | Predicted: Association
222/2326 | Gold: Association | Predicted: Association
223/2326 | Gold: Association | Predicted: Association
224/2326 | Gold: Association | Predicted: Association
225/2326 | Gold: Association | Predicted: Association
Checkpoint saved at 225 predictions.
226/2326 | Gold: Association | Predicted: Association
227/2326 | Gold: Association | Predicted: Association
228/2326 | Gold: Association | Predicted: Association
229/2326 | Gold: Positive_Correlation | Predicted: Association
230/2326 | Gold: Association | Predicted: No_Relation
231/2326 | Gold: Association | Predicted: No_Relation
232/2326 | Gold: Association | Predicted: Association
233/2326 | Gold: Association | Predicted: Association
234/2326 | Gold: Association | Predicted: Association
235/2326 | Gold: Association | Predicted: Association
236/2326 | Gold: Negative_Correlation | Predicted: No_Relation
237/2326 | Gold: Negative_Correlation | Predicted: No_Relation
238/2326 | Gold: Positive_Correlation | Predicted: Association
239/2326 | Gold: Association | Predicted: Negative_Correlation
240/2326 | Gold: Association | Predicted: Negative_Correlation
241/2326 | Gold: Association | Predicted: Negative_Correlation
242/2326 | Gold: Association | Predicted: No_Relation
243/2326 | Gold: Association | Predicted: No_Relation
244/2326 | Gold: Association | Predicted: No_Relation
245/2326 | Gold: Association | Predicted: Positive_Correlation
246/2326 | Gold: Positive_Correlation | Predicted: Negative_Correlation
247/2326 | Gold: Positive_Correlation | Predicted: Negative_Correlation
248/2326 | Gold: Positive_Correlation | Predicted: Negative_Correlation
249/2326 | Gold: Positive_Correlation | Predicted: Negative_Correlation
250/2326 | Gold: Positive_Correlation | Predicted: Negative_Correlation
Checkpoint saved at 250 predictions.
251/2326 | Gold: Positive_Correlation | Predicted: Negative_Correlation
252/2326 | Gold: Positive_Correlation | Predicted: Association
253/2326 | Gold: Association | Predicted: Negative_Correlation
254/2326 | Gold: Positive_Correlation | Predicted: Association
255/2326 | Gold: Negative_Correlation | Predicted: No_Relation
256/2326 | Gold: Negative_Correlation | Predicted: No_Relation
257/2326 | Gold: Negative_Correlation | Predicted: No_Relation
258/2326 | Gold: Negative_Correlation | Predicted: Negative_Correlation
259/2326 | Gold: Negative_Correlation | Predicted: No_Relation
260/2326 | Gold: Negative_Correlation | Predicted: Negative_Correlation
261/2326 | Gold: Negative_Correlation | Predicted: Negative_Correlation
262/2326 | Gold: Positive_Correlation | Predicted: Negative_Correlation
263/2326 | Gold: Positive_Correlation | Predicted: No_Relation
264/2326 | Gold: Positive_Correlation | Predicted: Negative_Correlation
265/2326 | Gold: Positive_Correlation | Predicted: Negative_Correlation
266/2326 | Gold: Positive_Correlation | Predicted: Negative_Correlation
267/2326 | Gold: Association | Predicted: Positive_Correlation
268/2326 | Gold: Positive_Correlation | Predicted: Association
269/2326 | Gold: Positive_Correlation | Predicted: Association
270/2326 | Gold: Negative_Correlation | Predicted: Association
271/2326 | Gold: Association | Predicted: Positive_Correlation
272/2326 | Gold: Positive_Correlation | Predicted: No_Relation
273/2326 | Gold: Association | Predicted: Negative_Correlation
274/2326 | Gold: Positive_Correlation | Predicted: No_Relation
275/2326 | Gold: Association | Predicted: Positive_Correlation
Checkpoint saved at 275 predictions.
276/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
277/2326 | Gold: Association | Predicted: Positive_Correlation
278/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
279/2326 | Gold: Association | Predicted: Positive_Correlation
280/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
281/2326 | Gold: Association | Predicted: Positive_Correlation
282/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
283/2326 | Gold: Association | Predicted: Positive_Correlation
284/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
285/2326 | Gold: Association | Predicted: Positive_Correlation
286/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
287/2326 | Gold: Association | Predicted: Positive_Correlation
288/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
289/2326 | Gold: Association | Predicted: Positive_Correlation
290/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
291/2326 | Gold: Association | Predicted: Association
292/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
293/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
294/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
295/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
296/2326 | Gold: Association | Predicted: Positive_Correlation
297/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
298/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
299/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
300/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
Checkpoint saved at 300 predictions.
301/2326 | Gold: Positive_Correlation | Predicted: Positive_Correlation
302/2326 | Gold: Positive_Correlation | Predicted: Association
303/2326 | Gold: Association | Predicted: No_Relation
304/2326 | Gold: Association | Predicted: Association
305/2326 | Gold: Association | Predicted: No_Relation
306/2326 | Gold: Association | Predicted: Association
307/2326 | Gold: Association | Predicted: Association
308/2326 | Gold: Association | Predicted: Bind
309/2326 | Gold: Association | Predicted: Bind
310/2326 | Gold: Association | Predicted: Positive_Correlation
311/2326 | Gold: Positive_Correlation | Predicted: No_Relation
312/2326 | Gold: Positive_Correlation | Predicted: No_Relation
313/2326 | Gold: Association | Predicted: Positive_Correlation
314/2326 | Gold: Association | Predicted: Positive_Correlation
315/2326 | Gold: Association | Predicted: Positive_Correlation

In [55]:
# Stage 5.9C - Save Final Test Predictions

with open(TEST_FINAL_PATH, "wb") as f:
    pickle.dump(test_predictions, f)

print("Final test predictions saved.")
print("Total predictions:", len(test_predictions))
print("Saved to:", TEST_FINAL_PATH)

Final test predictions saved.
Total predictions: 2326
Saved to: /content/drive/MyDrive/Capstone_Project/Stage_5_LLM_RE/test_predictions_final.pkl

In [56]:
# Stage 5.10A - Validate Completed Test Predictions

total_predictions = len(test_predictions)

valid_json_count = sum(
    result["valid_json"]
    for result in test_predictions
)

valid_relation_count = sum(
    result["valid_relation"]
    for result in test_predictions
)

none_prediction_count = sum(
    result["predicted_relation"] is None
    for result in test_predictions
)

print("Total test predictions:", total_predictions)
print("Valid JSON:", f"{valid_json_count}/{total_predictions}")
print("Valid relation labels:", f"{valid_relation_count}/{total_predictions}")
print("Invalid / None predictions:", none_prediction_count)

Total test predictions: 2326
Valid JSON: 2326/2326
Valid relation labels: 2281/2326
Invalid / None predictions: 45

In [57]:
# Stage 5.10B - Evaluate Test Set

evaluate_relation_predictions(test_predictions)

Accuracy: 0.5331

Macro Average
Precision: 0.3405
Recall:    0.6231
F1:        0.3873

Weighted Average
Precision: 0.5621
Recall:    0.5331
F1:        0.5431

Per-Class Results

                      precision    recall  f1-score   support

         Association     0.4095    0.2992    0.3458       635
                Bind     0.0667    0.3333    0.1111         9
          Comparison     0.4000    0.6667    0.5000         6
          Conversion     0.1250    1.0000    0.2222         1
         Cotreatment     0.5500    0.7857    0.6471        14
    Drug_Interaction     0.1176    1.0000    0.2105         2
Negative_Correlation     0.3158    0.4211    0.3609       171
Positive_Correlation     0.3264    0.3877    0.3544       325
         No_Relation     0.7534    0.7145    0.7335      1163

           micro avg     0.5436    0.5331    0.5383      2326
           macro avg     0.3405    0.6231    0.3873      2326
        weighted avg     0.5621    0.5331    0.5431      2326

In [2]:
# Stage 5.11A - Reload Final Qwen Test Predictions

from google.colab import drive
drive.mount("/content/drive")

import pickle
from pathlib import Path

PROJECT_DIR = Path("/content/drive/MyDrive/Capstone_Project")
STAGE_5_DIR = PROJECT_DIR / "Stage_5_LLM_RE"

TEST_FINAL_PATH = STAGE_5_DIR / "test_predictions_final.pkl"

with open(TEST_FINAL_PATH, "rb") as f:
    test_predictions = pickle.load(f)

print("Loaded Qwen test predictions:", len(test_predictions))

Mounted at /content/drive
Loaded Qwen test predictions: 2326

In [3]:
# Stage 5.11B - Load PubMedBERT RE Final Test Results

import json
from pathlib import Path

STAGE_3_3_DIR = PROJECT_DIR / "Stage_3_3_Outputs"

print("Stage 3.3 folders:")
for path in STAGE_3_3_DIR.iterdir():
    print("-", path.name)

Stage 3.3 folders:
- PubMedBERT_RE_Weighted_Final

In [4]:
# Stage 5.11C - Load PubMedBERT RE Final Test Results

PUBMEDBERT_RE_DIR = (
    STAGE_3_3_DIR / "PubMedBERT_RE_Weighted_Final"
)

PUBMEDBERT_RESULTS_PATH = (
    PUBMEDBERT_RE_DIR / "final_test_results.json"
)

with open(PUBMEDBERT_RESULTS_PATH, "r") as f:
    pubmedbert_test_results = json.load(f)

print("PubMedBERT RE final test results:\n")
print(pubmedbert_test_results)

PubMedBERT RE final test results:

{'model': 'microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract', 'loss_method': 'class_weighted_cross_entropy', 'training_examples': 8340, 'development_examples': 2313, 'test_examples': 2300, 'test_accuracy': 0.6983, 'test_macro_precision': 0.4667, 'test_macro_recall': 0.3539, 'test_macro_f1': 0.3644, 'test_weighted_precision': 0.6955, 'test_weighted_recall': 0.6983, 'test_weighted_f1': 0.6907}

In [7]:
# Stage 5.11D - Restore Relation Labels

RELATION_LABELS = [
    "Association",
    "Bind",
    "Comparison",
    "Conversion",
    "Cotreatment",
    "Drug_Interaction",
    "Negative_Correlation",
    "Positive_Correlation",
    "No_Relation"
]

print("Relation labels restored:", len(RELATION_LABELS))

Relation labels restored: 9

In [8]:
# Stage 5.11E - Compare PubMedBERT and Qwen Relation Extraction Results

import pandas as pd
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

# Recompute Qwen test metrics directly from saved predictions
qwen_y_true = [
    result["gold_relation"]
    for result in test_predictions
]

qwen_y_pred = [
    result["predicted_relation"]
    if result["predicted_relation"] is not None
    else "__INVALID__"
    for result in test_predictions
]

qwen_accuracy = accuracy_score(qwen_y_true, qwen_y_pred)

qwen_macro_precision, qwen_macro_recall, qwen_macro_f1, _ = (
    precision_recall_fscore_support(
        qwen_y_true,
        qwen_y_pred,
        labels=RELATION_LABELS,
        average="macro",
        zero_division=0
    )
)

qwen_weighted_precision, qwen_weighted_recall, qwen_weighted_f1, _ = (
    precision_recall_fscore_support(
        qwen_y_true,
        qwen_y_pred,
        labels=RELATION_LABELS,
        average="weighted",
        zero_division=0
    )
)

comparison_df = pd.DataFrame({
    "Metric": [
        "Test Examples",
        "Accuracy",
        "Macro Precision",
        "Macro Recall",
        "Macro F1",
        "Weighted Precision",
        "Weighted Recall",
        "Weighted F1"
    ],
    "PubMedBERT": [
        pubmedbert_test_results["test_examples"],
        pubmedbert_test_results["test_accuracy"],
        pubmedbert_test_results["test_macro_precision"],
        pubmedbert_test_results["test_macro_recall"],
        pubmedbert_test_results["test_macro_f1"],
        pubmedbert_test_results["test_weighted_precision"],
        pubmedbert_test_results["test_weighted_recall"],
        pubmedbert_test_results["test_weighted_f1"]
    ],
    "Qwen2.5-7B Few-Shot": [
        len(test_predictions),
        qwen_accuracy,
        qwen_macro_precision,
        qwen_macro_recall,
        qwen_macro_f1,
        qwen_weighted_precision,
        qwen_weighted_recall,
        qwen_weighted_f1
    ]
})

display(comparison_df)

               Metric  PubMedBERT  Qwen2.5-7B Few-Shot
0       Test Examples   2300.0000          2326.000000
1            Accuracy      0.6983             0.533104
2     Macro Precision      0.4667             0.340490
3        Macro Recall      0.3539             0.623134
4            Macro F1      0.3644             0.387275
5  Weighted Precision      0.6955             0.562070
6     Weighted Recall      0.6983             0.533104
7         Weighted F1      0.6907             0.543067

### Relation Extraction Comparison Summary

PubMedBERT achieved stronger overall relation extraction performance, with higher accuracy (**69.83%**) and weighted F1 (**69.07%**) compared with Qwen2.5-7B few-shot extraction (**53.31% accuracy; 54.31% weighted F1**).

Qwen achieved substantially higher macro recall (**62.31% vs 35.39%**) and a slightly higher macro F1 (**38.73% vs 36.44%**), suggesting that the few-shot LLM was more sensitive to minority relation classes but produced more false-positive classifications.

Overall, PubMedBERT provided more reliable performance across the imbalanced BioRED relation dataset, whereas Qwen demonstrated greater recall across relation categories without task-specific fine-tuning.

**Evaluation note:** PubMedBERT was evaluated on **2,300** test examples after truncation-related marker-problem examples were excluded, while Qwen was evaluated on all **2,326** prepared test relation examples.